INSERT INTO airlines (airline_id, icao, name, callsign,forsource,active) VALUES
(1, 'ABD', 'Air Atlanta Icelandic', 'Atlanta','vatsim','Y'),
(2, 'ABB', 'Air Belgium', 'Air Belgium','vatsim','Y'),
(3, 'AAR', 'Asiana Airlines', 'Asiana','vatsim','Y'),
(4, 'AAL', 'American Airlines', 'American','vatsim','Y'),
(5, 'AAH', 'Aloha Airlines', 'Aloha','vatsim','Y'),
(6, 'AAG', 'Air Atlantique', 'Atlantic','vatsim','Y'),
(7, 'AAA', 'Ansett Australia', 'Ansett','vatsim','Y'),
(8, 'ABQ', 'Albion Air Cargo', 'Albion','vatsim','Y'),
(9, 'ABR', 'Air Contractors', 'Contract','vatsim','Y'),
(10, 'ABX', 'Airborne Express', 'Abex','vatsim','Y'),
(11, 'ABY', 'Air Arabia', 'Arabia','vatsim','Y'),
(12, 'ACA', 'Air Canada', 'Air Canada','vatsim','Y'),
(13, 'ACD', 'Air Canadian', 'Air Canadian','vatsim','Y'),
(14, 'ACE', 'Air Cargo Express', 'Air Cargo','vatsim','Y'),
(15, 'ACQ', 'Aero Continente', 'Aero Continente','vatsim','Y'),
(16, 'ADB', 'Antonov Design Bureau', 'Antonov','vatsim','Y'),
(17, 'ADH', 'Air One', 'Heron','vatsim','Y'),
(18, 'ADN', 'Aerodienst', 'Aerodienst','vatsim','Y'),
(19, 'ADO', 'Air Do', 'Air Do','vatsim','Y'),
(20, 'ADR', 'Adria Airways', 'Adria','vatsim','Y'),
(21, 'ADV', 'AirDolomiti Virtual', 'AirDolomiti','vatsim','Y'),
(22, 'AEA', 'Air Europa', 'Air Europa','vatsim','Y'),
(23, 'AEB', 'AEBR - Aero Brasil', '','vatsim','Y'),
(24, 'AEC', 'Aerocol', '','vatsim','Y'),
(25, 'AEE', 'Aegean Airlines', 'Aegean','vatsim','Y'),
(26, 'AEF', 'Aero Lloyd', 'Aero Lloyd','vatsim','Y'),
(27, 'AEL', 'Air Europe Italy', 'Europe Italy','vatsim','Y'),
(28, 'AES', 'ACES Colombia', 'Aces','vatsim','Y'),
(29, 'AEU', 'Astraeus', 'Flystar','vatsim','Y'),
(30, 'AEW', 'Aerosvit Airlines', 'Aerosvit','vatsim','Y'),
(31, 'AEY', 'Air Italy', 'Air Italy','vatsim','Y'),
(32, 'AFA', 'American Flight Airways', 'AFA','vatsim','Y'),
(33, 'AFG', 'Ariana Afghan Airlines', 'Ariana','vatsim','Y'),
(34, 'AFL', 'Aeroflot', 'Aeroflot','vatsim','Y'),
(35, 'AFR', 'Air France', 'Air France','vatsim','Y'),
(36, 'AFX', 'African Express', '','vatsim','Y'),
(37, 'AGA', 'Air Germany VA', '','vatsim','Y'),
(38, 'AGN', 'Air Gabon', 'Air Gabon','vatsim','Y'),
(39, 'AHR', 'Air Holland', '','vatsim','Y'),
(40, 'AHS', 'AirHispania', 'Air Hispania','vatsim','Y'),
(41, 'AIB', 'Airbus Industrie', 'Airbus Industrie','vatsim','Y'),
(42, 'AIC', 'Air India', 'Air India','vatsim','Y'),
(43, 'AIE', 'Air Inuit', 'Air Inuit','vatsim','Y'),
(44, 'AIH', 'Airtours International', 'Kestrel','vatsim','Y'),
(45, 'AIM', 'Mochuelo Airlines', 'Mochuelo','vatsim','Y'),
(46, 'AIZ', 'Arkia Israel Airlines', 'Arkia','vatsim','Y'),
(47, 'AJM', 'Air Jamaica', 'Air Jamaica','vatsim','Y'),
(48, 'AJY', 'Ajet', 'Helios','vatsim','Y'),
(49, 'AKG', 'Aero Companies 2000', '','vatsim','Y'),
(50, 'AKK', 'Aklak Air', 'Aklak','vatsim','Y'),
(51, 'AKN', 'Alkan Air', 'Alkan Air','vatsim','Y'),
(52, 'ALK', 'Sri Lankan Airlines', 'SriLankan','vatsim','Y'),
(53, 'ALO', 'USAirways Express', 'Allegheny','vatsim','Y'),
(54, 'ALT', 'Altair Virtual Airlines', 'Altair','vatsim','Y'),
(55, 'ALZ', 'Al Andalus Airlines', 'Andalus','vatsim','Y'),
(56, 'AMC', 'Air Malta', 'Air Malta','vatsim','Y'),
(57, 'AMM', 'Air 2000', 'Jetset','vatsim','Y'),
(58, 'AMT', 'ATA Airlines', 'Amtran','vatsim','Y'),
(59, 'AMX', 'Aeromexico', 'Aeromexico','vatsim','Y'),
(60, 'ANA', 'All Nippon Airways', 'All nippon','vatsim','Y'),
(61, 'ANX', 'Canadian North', 'Empress','vatsim','Y'),
(62, 'ANZ', 'Air New Zealand', 'Air New zealand','vatsim','Y'),
(63, 'API', 'Air Palma International Airways', 'AirPalma','vatsim','Y'),
(64, 'APN', 'Air Polonia', 'Air Polonia','vatsim','Y'),
(65, 'ARD', 'Aerocondor', 'Aerocondor','vatsim','Y'),
(66, 'ARE', 'Aires Colombia', 'Aires','vatsim','Y'),
(67, 'ARF', 'Aero Flight', 'Aero Fox','vatsim','Y'),
(68, 'ARG', 'Aerolineas Argentinas', 'Argentina','vatsim','Y'),
(69, 'ASA', 'Alaska Airlines', 'Alaska','vatsim','Y'),
(70, 'ASD', 'AeroSarda', 'Sarda','vatsim','Y'),
(71, 'ASE', 'Aegean Seagull', 'Seagull','vatsim','Y'),
(72, 'ASH', 'Mesa Airlines', 'Air Shuttle','vatsim','Y'),
(73, 'ASO', 'AirSource', '','vatsim','Y'),
(74, 'ASQ', 'Atlantic Southeast Airlines', 'Acey','vatsim','Y'),
(75, 'ASZ', 'Astrakhan Airlines', 'Air Astrakhan','vatsim','Y'),
(76, 'ATX', 'AeroTexas Aviation International', 'AeroTexas','vatsim','Y'),
(77, 'AUA', 'Austrian Airlines', 'Austrian','vatsim','Y'),
(78, 'AUB', 'Augsburg Airways', 'Augsburg Air','vatsim','Y'),
(79, 'AUH', 'Amiri Flight', 'Sultan','vatsim','Y'),
(80, 'AUI', 'Ukraine International Airlines', 'Ukraine International','vatsim','Y'),
(81, 'AUR', 'Aurigny Air Services', 'Ayline','vatsim','Y'),
(82, 'AUT', 'Austral Lineas Aereas', 'Austral','vatsim','Y'),
(83, 'AUZ', 'Australian Airlines', 'Australian','vatsim','Y'),
(84, 'AVA', 'Avianca', 'Avianca','vatsim','Y'),
(85, 'AVE', 'AVENSA', 'AlphaVictorEcho','vatsim','Y'),
(86, 'AVQ', 'AeroVirtuel Quebec', '','vatsim','Y'),
(87, 'AWC', 'Titan Airways', 'Zap','vatsim','Y'),
(88, 'AWE', 'US Airways', 'Cactus','vatsim','Y'),
(89, 'AWI', 'Air Wisconsin', 'Air Wisconsin','vatsim','Y'),
(90, 'AWW', 'Air Wales', 'Red Dragon','vatsim','Y'),
(91, 'AXM', 'AirAsia', 'Asian Express','vatsim','Y'),
(92, 'AXO', 'Axon Airlines', 'Axon','vatsim','Y'),
(93, 'AXY', 'Axis Airways', 'Axis','vatsim','Y'),
(94, 'AZA', 'Alitalia', 'Alitalia','vatsim','Y'),
(95, 'AZH', 'Azahar Airlines', 'Azahar','vatsim','Y'),
(96, 'BAC', 'Buenos Aires Cubs Flying Group', 'Baires Cub','vatsim','Y'),
(97, 'BAL', 'Britannia Airways', 'Britannia','vatsim','Y'),
(98, 'BAW', 'British Airways', 'Speedbird','vatsim','Y'),
(99, 'BBC', 'Biman Bangladesh Airlines', 'Bangladesh','vatsim','Y'),
(100, 'BBO', 'Flybaboo Airways', 'Baboo','vatsim','Y'),
(101, 'BBR', 'Santa Barbara Airlines', 'Barbara','vatsim','Y'),
(102, 'BCA', 'Britannic Virtual Airlines', 'Britannic','vatsim','Y'),
(103, 'BCS', 'European Air Transport', 'Eurotrans','vatsim','Y'),
(104, 'BCY', 'Cityjet', 'City-Ireland','vatsim','Y'),
(105, 'BDA', 'Business Direct Airlines', '','vatsim','Y'),
(106, 'BEE', 'Flybe', 'Jersey','vatsim','Y'),
(107, 'BER', 'Air Berlin', 'Air Berlin','vatsim','Y'),
(108, 'BFL', 'Buffalo Airways', 'Buffalo','vatsim','Y'),
(109, 'BGA', 'Airbus Transport International', 'Super Transport','vatsim','Y'),
(110, 'BHP', 'Belair', 'Belair','vatsim','Y'),
(111, 'BIH', 'British International', 'Brintel','vatsim','Y'),
(112, 'BLF', 'Blue1', 'Bluefinn','vatsim','Y'),
(113, 'BLS', 'Bearskin Airlines', 'Bearskin','vatsim','Y'),
(114, 'BLX', 'TUIfly Nordic', 'Bluescan','vatsim','Y'),
(115, 'BMA', 'British Midland Airways', 'Midland','vatsim','Y'),
(116, 'BMI', 'bmibaby', 'Baby','vatsim','Y'),
(117, 'BNF', 'Braniff International', 'Braniff','vatsim','Y'),
(118, 'BNW', 'British Northwest Airlines', 'British North','vatsim','Y'),
(119, 'BOG', 'Breogan Airways', 'Breogan','vatsim','Y'),
(120, 'BOV', 'Bomsucesso Virtual', 'Bomsucesso','vatsim','Y'),
(121, 'BPA', 'Blue Panorama', 'Blue Panorama','vatsim','Y'),
(122, 'BRA', 'Braathens', 'Braathens','vatsim','Y'),
(123, 'BRB', 'BRA Transportes Aeroes', 'Brasair','vatsim','Y'),
(124, 'BRC', 'Brasil Continental', '','vatsim','Y'),
(125, 'BRT', 'BA Connect', 'British','vatsim','Y'),
(126, 'BRU', 'Belavia', 'Balarus Avia','vatsim','Y'),
(127, 'BRW', 'Bahines Stream Airways', 'Bahines','vatsim','Y'),
(128, 'BRZ', 'Samara Airlines', 'Beryoza','vatsim','Y'),
(129, 'BTA', 'ExpressJet Airlines', 'JetLink','vatsim','Y'),
(130, 'BTC', 'Bashkir Airlines', 'Bashirian','vatsim','Y'),
(131, 'BTI', 'Air Baltic', 'Airbaltic','vatsim','Y'),
(132, 'BTW', 'BlueTwilight Airlines', 'Twilight','vatsim','Y'),
(133, 'BUB', 'Air Bourbon', 'Bourbon','vatsim','Y'),
(134, 'BUZ', 'Buzz Stansted Ltd.', 'Buss','vatsim','Y'),
(135, 'BVA', 'Belgium Virtual Airline', '','vatsim','Y'),
(136, 'BWA', 'Caribbean Airlines', 'Caribbean Airlines','vatsim','Y'),
(137, 'BWG', 'Blue Wings', 'Blue wings','vatsim','Y'),
(138, 'BXS', 'Spantax', 'Spantax','vatsim','Y'),
(139, 'BZH', 'Brit Air', 'Britair','vatsim','Y'),
(140, 'CAL', 'China Airlines', 'Dynasty','vatsim','Y'),
(141, 'CAV', 'Calm Air', 'Calm Air','vatsim','Y'),
(142, 'CAW', 'Kulula.com', 'Kulula','vatsim','Y'),
(143, 'CBF', 'China Northern Airlines', 'China Northern','vatsim','Y'),
(144, 'CCA', 'Air China', 'Air China','vatsim','Y'),
(145, 'CCM', 'CCM Airlines', 'Corsica','vatsim','Y'),
(146, 'CDN', 'Canadian Airlines International', 'Canadian','vatsim','Y'),
(147, 'CEA', 'Central European', 'Central European','vatsim','Y'),
(148, 'CEB', 'Cebu Pacific Air', 'Cebu Pacific','vatsim','Y'),
(149, 'CES', 'China Eastern Airlines', 'China Eastern','vatsim','Y'),
(150, 'CFG', 'Condor Flugdienst', 'Condor','vatsim','Y'),
(151, 'CHH', 'Hainan Airlines', 'Hainan','vatsim','Y'),
(152, 'CHP', 'Aviacsa', 'Aviacsa','vatsim','Y'),
(153, 'CHQ', 'Chautauqua Airlines', 'Chautauqua','vatsim','Y'),
(154, 'CIM', 'Cimber Air', 'Cimber','vatsim','Y'),
(155, 'CIN', 'Constellation', 'Constellation','vatsim','Y'),
(156, 'CIP', 'City Air', 'Cityways','vatsim','Y'),
(157, 'CIU', 'Cielos del Peru', 'Cielos','vatsim','Y'),
(158, 'CJA', 'Canjet', 'Canjet','vatsim','Y'),
(159, 'CJC', 'Colgan Air', 'Colgan','vatsim','Y'),
(160, 'CJT', 'Cargojet', 'Cargojet','vatsim','Y'),
(161, 'CKS', 'Kalitta Air', 'Connie','vatsim','Y'),
(162, 'CLF', 'Bristol Flying Centre', 'Clifton','vatsim','Y'),
(163, 'CLH', 'Lufthansa CityLine', 'Hansaline','vatsim','Y'),
(164, 'CLW', 'Centralwings', 'Centralwings','vatsim','Y'),
(165, 'CLX', 'Cargolux Airlines International', 'Cargolux','vatsim','Y'),
(166, 'CMM', 'Canada 3000 Airlines', 'Elite','vatsim','Y'),
(167, 'CMP', 'Copa Airlines', 'Copa','vatsim','Y'),
(168, 'CND', 'Aero Continente Dominicana', 'Condominicana','vatsim','Y'),
(169, 'CNN', 'Connect Virtual Airlines', 'Connair','vatsim','Y'),
(170, 'CNO', 'SAS Braathens', 'Scanor','vatsim','Y'),
(171, 'CNR', 'CANair', '','vatsim','Y'),
(172, 'CNS', 'Conesul VA', 'Conesul','vatsim','Y'),
(173, 'CNW', 'China Northwest Airlines', 'China Northwest','vatsim','Y'),
(174, 'COA', 'Continental Air Lines', 'Continental','vatsim','Y'),
(175, 'COM', 'Comair', 'Comair','vatsim','Y'),
(176, 'CPA', 'Cathay Pacific Airways', 'Cathay','vatsim','Y'),
(177, 'CPC', 'CP Air', 'Empress','vatsim','Y'),
(178, 'CRA', 'CR Airways', 'China Rich','vatsim','Y'),
(179, 'CRG', 'Cargoitalia', 'White Pelican','vatsim','Y'),
(180, 'CRL', 'TUI Corsair', 'Corsair','vatsim','Y'),
(181, 'CRQ', 'Air Creebec', 'Cree','vatsim','Y'),
(182, 'CRX', 'Swiss Airlines', 'Swiss','vatsim','Y'),
(183, 'CRZ', 'Cruzeiro Do Sul', 'Cruzeiro','vatsim','Y'),
(184, 'CSA', 'CSA Czech Airlines', 'CSA Lines','vatsim','Y'),
(185, 'CSE', 'CSE Aviation', 'Oxford','vatsim','Y'),
(186, 'CSN', 'China Southern Airlines', 'China Southern','vatsim','Y'),
(187, 'CST', 'Coast Air', 'Coast Center','vatsim','Y'),
(188, 'CSZ', 'Shenzhen Airlines', 'Shenzhen Air','vatsim','Y'),
(189, 'CTB', 'City Bird', 'Dream Bird','vatsim','Y'),
(190, 'CTN', 'Croatia Airlines', 'Croatia','vatsim','Y'),
(191, 'CUA', 'China United Airlines', 'Lianhang','vatsim','Y'),
(192, 'CUB', 'Cubana De Aviacion', 'Cubana','vatsim','Y'),
(193, 'CUS', 'Cronus Airlines', 'Cronus','vatsim','Y'),
(194, 'CVA', 'Canadian Virtual Airlines', 'Canadian','vatsim','Y'),
(195, 'CVI', 'Conviasa', 'Conviasa','vatsim','Y'),
(196, 'CVV', 'Cabo Verde Airlines VA', 'CaboVerde','vatsim','Y'),
(197, 'CWV', 'Ca.Airways', 'Bluebird','vatsim','Y'),
(198, 'CXA', 'Canadian Xpress', 'Canadian Xpress','vatsim','Y'),
(199, 'CXH', 'China Xinhua Airlines', 'Xinhua','vatsim','Y'),
(200, 'CXJ', 'China Xinjiang Airlines', 'Xinjian','vatsim','Y'),
(201, 'CXN', 'China Southwest Airlines', 'China Southwest','vatsim','Y'),
(202, 'CYA', 'Cuyabra', '','vatsim','Y'),
(203, 'CYB', 'Cyber Air', 'Cyber','vatsim','Y'),
(204, 'CYH', 'China Yunnan Airlines', 'Yunnan','vatsim','Y'),
(205, 'CYP', 'Cyprus Airways', 'Cyprus','vatsim','Y'),
(206, 'DAH', 'Air Algerie', 'Air Algerie','vatsim','Y'),
(207, 'DAL', 'Delta Air Lines', 'Delta','vatsim','Y'),
(208, 'DAN', 'Maersk Air', 'Maersk Air','vatsim','Y'),
(209, 'DAT', 'Brussels Airlines', 'Estail','vatsim','Y'),
(210, 'DAW', 'Duo Airways', 'Flyduo','vatsim','Y'),
(211, 'DBR', 'Dutchbird', 'Dutchbrird','vatsim','Y'),
(212, 'DCA', 'DC3 Airways', 'Airways','vatsim','Y'),
(213, 'DFV', 'Germany South Virtual Airlines', '','vatsim','Y'),
(214, 'DGF', 'DragonFlight', 'Dragonflight','vatsim','Y'),
(215, 'DHI', 'Adam Air', 'Adam Sky','vatsim','Y'),
(216, 'DHK', 'DHL Air', 'Eurotrans','vatsim','Y'),
(217, 'DHL', 'Astar Air Cargo', 'Dahl','vatsim','Y'),
(218, 'DIS', 'InterSim', 'intersim-va.de/2','vatsim','Y'),
(219, 'DLA', 'Air Dolomiti', 'Dolomiti','vatsim','Y'),
(220, 'DLH', 'Lufthansa', 'Lufthansa','vatsim','Y'),
(221, 'DMO', 'Domodedovo Airlines', 'Domodedovo','vatsim','Y'),
(222, 'DNV', 'Aeroflot-Don', 'Donavia','vatsim','Y'),
(223, 'DOB', 'Dobrolet', 'Dobrolet','vatsim','Y'),
(224, 'DRK', 'Druk Air Corporation', 'Royal Bhutan','vatsim','Y'),
(225, 'DRV', 'Dracula Virtual Airlines', 'Dracula','vatsim','Y'),
(226, 'DTA', 'TAAG Air Angola', 'DTA','vatsim','Y'),
(227, 'DTR', 'Danish Air Transport', 'Danish','vatsim','Y'),
(228, 'DUA', 'Dutch-Air', 'Dutch-Air','vatsim','Y'),
(229, 'DVA', 'Delta Virtual Airlines', 'Delta','vatsim','Y'),
(230, 'EAA', 'EuropAir', '','vatsim','Y'),
(231, 'EAF', 'Palmair', 'Palmair','vatsim','Y'),
(232, 'EAL', 'Eastern Air Lines', 'Eastern','vatsim','Y'),
(233, 'EAY', 'Aero Airlines', 'Reval','vatsim','Y'),
(234, 'EBA', 'EuroBerlin Virtual Airlines', 'Euroberlin','vatsim','Y'),
(235, 'ECA', 'Eurocypria Airlines', 'Eurocypria','vatsim','Y'),
(236, 'EDW', 'Edelweiss Air', 'Edelweiss','vatsim','Y'),
(237, 'EEP', 'European Express VA', 'European','vatsim','Y'),
(238, 'EEZ', 'Eurofly', 'Siriofly','vatsim','Y'),
(239, 'EGF', 'American Eagle', 'Eagle Flight','vatsim','Y'),
(240, 'EHM', 'EuroHarmony Virtual Airline', 'EuroHarmony','vatsim','Y'),
(241, 'EHY', 'Ephesus VA', 'Efes','vatsim','Y'),
(242, 'EIA', 'Evergreen International Airlines', 'Evergreen','vatsim','Y'),
(243, 'EIN', 'Aer Lingus', 'Shamrock','vatsim','Y'),
(244, 'EJA', 'Netjets Aviation', 'execjet','vatsim','Y'),
(245, 'EKY', 'EuroSky VA', 'EuroSky','vatsim','Y'),
(246, 'ELG', 'Alpi Eagles', 'Alpi Eagles','vatsim','Y'),
(247, 'ELL', 'Estonian Air', 'Estonian','vatsim','Y'),
(248, 'ELO', 'Eurolot', 'Eurolot','vatsim','Y'),
(249, 'ELV', 'TANS Peru', 'Aereos Selva','vatsim','Y'),
(250, 'ELY', 'El Al', 'Elal','vatsim','Y'),
(251, 'EMD', 'Emerald Air', 'Emerald','vatsim','Y'),
(252, 'EMI', 'EmisphAir', '','vatsim','Y'),
(253, 'EMX', 'Euromanx', 'Euromanx','vatsim','Y'),
(254, 'ERO', 'Sun d''Or', 'Sundor','vatsim','Y'),
(255, 'ERT', 'Eritrean Airlines', 'Eritrean','vatsim','Y'),
(256, 'ESA', 'Eurostar Aviation', 'Eurostar','vatsim','Y'),
(257, 'ESK', 'Skyeurope Airlines', 'Relax','vatsim','Y'),
(258, 'ESL', 'Russian Sky Airlines', 'Eastline Express','vatsim','Y'),
(259, 'ESS', 'EOS Airlines', 'New Dawn','vatsim','Y'),
(260, 'ETD', 'Etihad Airways', 'Etihad','vatsim','Y'),
(261, 'ETH', 'Ethiopian Airlines', 'Ethiopian','vatsim','Y'),
(262, 'ETR', 'Eccentric Travels', 'Eccentric','vatsim','Y'),
(263, 'EUA', 'Europa Airways', '','vatsim','Y'),
(264, 'EUC', 'EuroConnect Airlines', 'Euroconnect','vatsim','Y'),
(265, 'EUY', 'EUjet', 'Euro Airways','vatsim','Y'),
(266, 'EVA', 'EVA Airways', 'EVA','vatsim','Y'),
(267, 'EWA', 'East-East-West Airlines', 'Eastwest','vatsim','Y'),
(268, 'EWG', 'Eurowings', 'Eurowings','vatsim','Y'),
(269, 'EWW', 'Emery Worldwide Airlines', 'Emery','vatsim','Y'),
(270, 'EXL', 'Sunshine Express Airline', '','vatsim','Y'),
(271, 'EXM', 'CAA Flight Examiners', 'Exam','vatsim','Y'),
(272, 'EXS', 'Jet2', 'Channex','vatsim','Y'),
(273, 'EZE', 'Eastern Airways', 'Eastflight','vatsim','Y'),
(274, 'EZS', 'Easy Jet Switzerland', 'Topswiss','vatsim','Y'),
(275, 'EZY', 'EasyJet', 'Easy','vatsim','Y'),
(276, 'FAV', 'Venezuelan Air Force', 'Fuerza Aerea Venezolana','vatsim','Y'),
(277, 'FCA', 'First Choice Airways', 'Jetset','vatsim','Y'),
(278, 'FCY', 'CyberAvia', 'Cyberavia','vatsim','Y'),
(279, 'FDX', 'Federal Express', 'FedEx','vatsim','Y'),
(280, 'FEA', 'Far Eastern Air Transport Corp', 'Far Eastern','vatsim','Y'),
(281, 'FFT', 'Frontier Airlines', 'Frontier','vatsim','Y'),
(282, 'FHE', 'Hello AG', 'FlyHello','vatsim','Y'),
(283, 'FHY', 'Freebird', 'Freebird','vatsim','Y'),
(284, 'FIF', 'Air Finland', 'Air Finland','vatsim','Y'),
(285, 'FIN', 'Finnair', 'Finnair','vatsim','Y'),
(286, 'SLR', 'Silverjet', 'Silverjet','vatsim','Y'),
(287, 'FJI', 'Air Pacific', 'Pacific','vatsim','Y'),
(288, 'FLG', 'Northwest Airlink', 'Flagship','vatsim','Y'),
(289, 'FLI', 'Atlantic Airways', 'Faroeline','vatsim','Y'),
(290, 'FLT', 'Flightline', 'Flightline','vatsim','Y'),
(291, 'FLY', 'FlyMe', 'Flybird','vatsim','Y'),
(292, 'FPO', 'Europe Airpost', 'French Post','vatsim','Y'),
(293, 'FSC', 'Flugsimulatorclub e.V.', 'Simclub','vatsim','Y'),
(294, 'FUA', 'Futura International Airways', 'Futura','vatsim','Y'),
(295, 'FWI', 'Air Cara?bes', 'French West','vatsim','Y'),
(296, 'FXI', 'Flugfelag Islands', 'Faxi','vatsim','Y'),
(297, 'FYN', 'Comfort Air', 'Flynn','vatsim','Y'),
(298, 'GAE', 'German Air Express', 'Express','vatsim','Y'),
(299, 'GAL', 'German Airlines', '','vatsim','Y'),
(300, 'GAO', 'Golden Air', 'Golden','vatsim','Y'),
(301, 'GBL', 'GB Airways', 'Gee Bee Airways','vatsim','Y'),
(302, 'GCO', 'Gemini Air Cargo', 'Gemini','vatsim','Y'),
(303, 'GDA', 'Gold Air International', 'Goldair','vatsim','Y'),
(304, 'GEC', 'Lufthansa Cargo', 'Lufthansa Cargo','vatsim','Y'),
(305, 'GEW', 'German Airways VA', 'Blueflight','vatsim','Y'),
(306, 'GFA', 'Gulf Air', 'Gulfair','vatsim','Y'),
(307, 'GFT', 'Gulfstream International Airlines', 'Gulf Flight','vatsim','Y'),
(308, 'GFV', 'German Flights VA', '','vatsim','Y'),
(309, 'GHA', 'Ghana Airways', 'Ghana ','vatsim','Y'),
(310, 'GIA', 'Garuda Indonesia', 'Indonesia','vatsim','Y'),
(311, 'GJT', 'Girjet', 'Banjet','vatsim','Y'),
(312, 'GLG', 'AeroGal', 'Aerogal','vatsim','Y'),
(313, 'XPE', 'XP-AIR', '','vatsim','Y'),
(314, 'GLR', 'Central Mountain Air', 'Glacier','vatsim','Y'),
(315, 'GMI', 'Germania', 'Germania','vatsim','Y'),
(316, 'GOC', 'German Overseas AirCargo', 'German Overseas','vatsim','Y'),
(317, 'GRE', 'Air Scotland', 'Greece Airways','vatsim','Y'),
(318, 'GRL', 'Air Greenland', 'Greenlandair','vatsim','Y'),
(319, 'GSM', 'Flyglobespan', 'Globespan','vatsim','Y'),
(320, 'GSS', 'Global Supply Systems', 'Jet Lift','vatsim','Y'),
(321, 'GSV', 'StuttgartAir', 'StuttgartAir','vatsim','Y'),
(322, 'GTI', 'Atlas Air', 'Giant','vatsim','Y'),
(323, 'GUA', 'Global United Air', '','vatsim','Y'),
(324, 'GVA', 'German Virtual AirForce', 'German Airforce','vatsim','Y'),
(325, 'GWG', 'German Airwings VA', '','vatsim','Y'),
(326, 'GWI', 'Germanwings', 'Germanwings','vatsim','Y'),
(327, 'GWY', 'USA 3000', 'Getaway','vatsim','Y'),
(328, 'GXL', 'Star German Airlines', 'Star Dust','vatsim','Y'),
(329, 'GXP', 'Global Xpression', '','vatsim','Y'),
(330, 'HAL', 'Hawaiian Airlines', 'Hawaiian','vatsim','Y'),
(331, 'HAM', 'Hamburg Air', 'HamburgAir','vatsim','Y'),
(332, 'HAW', 'Hughes Airwest', 'Airwest','vatsim','Y'),
(333, 'HDA', 'Dragonair', 'Dragon','vatsim','Y'),
(334, 'HEJ', 'Hellas Jet', 'Hellas Jet','vatsim','Y'),
(335, 'HFY', 'HiFly', 'Sky Flyer','vatsim','Y'),
(336, 'HHI', 'Hamburg International', 'Hamburg Jet','vatsim','Y'),
(337, 'HHK', 'Hong Kong Express Airways', 'Hongkong Shuttle','vatsim','Y'),
(338, 'HLF', 'TUIfly', 'Yellow Cab','vatsim','Y'),
(339, 'HLN', 'Air Holland', 'Orange','vatsim','Y'),
(340, 'HLX', 'TUIfly', 'Yellow Cab','vatsim','Y'),
(341, 'HMY', 'HMY Airways', 'Harmony','vatsim','Y'),
(342, 'HSK', 'Sky Europe Airlines Hungary', 'Matra','vatsim','Y'),
(343, 'HST', 'Hellenic Star Airways', 'Hellenic Star','vatsim','Y'),
(344, 'HVN', 'Vietnam Airlines', 'Vietnam Airlines','vatsim','Y'),
(345, 'HWY', 'Highland Airways', 'Hiway','vatsim','Y'),
(346, 'IAC', 'Indian Airlines', 'Indair','vatsim','Y'),
(347, 'IBB', 'Binter Canarias', 'Binter','vatsim','Y'),
(348, 'IBE', 'Iberia', 'Iberia','vatsim','Y'),
(349, 'ICB', 'Islandsflug', 'Icebird','vatsim','Y'),
(350, 'ICE', 'Icelandair', 'Ice Air','vatsim','Y'),
(351, 'IDE', 'Independence Air', 'Independence Air','vatsim','Y'),
(352, 'IOS', 'Isles of Scilly Skybus', 'Scillonia','vatsim','Y'),
(353, 'IRA', 'Iran Air', 'Iranair','vatsim','Y'),
(354, 'IRM', 'Mahan Airlines', 'Mahan Air','vatsim','Y'),
(355, 'ISK', 'InterSky', 'Intersky','vatsim','Y'),
(356, 'ISR', 'Israir Airlines', 'Israir','vatsim','Y'),
(357, 'ISS', 'Meridiana', 'Merair','vatsim','Y'),
(358, 'ITC', 'ItalianCharter Team', 'ItalianCharter','vatsim','Y'),
(359, 'IWD', 'Iberworld Airlines', 'Iberworld','vatsim','Y'),
(360, 'IYE', 'Yemenia', 'Yemeni','vatsim','Y'),
(361, 'JAA', 'Japan Asia Airways', 'Asia','vatsim','Y'),
(362, 'JAE', 'Jade Cargo', 'Jade Cargo','vatsim','Y'),
(363, 'JAI', 'Jet Airways', 'Jet Airways','vatsim','Y'),
(364, 'JAL', 'Japan Airlines', 'Japanair','vatsim','Y'),
(365, 'JAS', 'Japan Air System', 'Air System','vatsim','Y'),
(366, 'JAT', 'Jat Airways', 'Jat','vatsim','Y'),
(367, 'JBA', 'Helijet Airways', 'Helijet','vatsim','Y'),
(368, 'JBU', 'JetBlue Airways', 'JetBlue','vatsim','Y'),
(369, 'JDA', 'Jet Direct Airlines', 'Jet Direct','vatsim','Y'),
(370, 'JEM', 'Emerald Airways', 'Gemstone','vatsim','Y'),
(371, 'JET', 'Wind Jet', 'Ghibli','vatsim','Y'),
(372, 'JFU', 'Jet4You', 'Argan','vatsim','Y'),
(373, 'JGO', 'Jetsgo', 'Jetsgo','vatsim','Y'),
(374, 'JKK', 'Spanair', 'Spanair','vatsim','Y'),
(375, 'JMC', 'JMC Airlines', 'JayEmmSee','vatsim','Y'),
(376, 'JSA', 'Jetstar Asia Airways', 'JetStarAsia','vatsim','Y'),
(377, 'JST', 'Jetstar Airways', 'Jetstar','vatsim','Y'),
(378, 'JXX', 'JetX Airlines', 'Jetbird','vatsim','Y'),
(379, 'JZA', 'Air Canada Jazz', 'Jazz','vatsim','Y'),
(380, 'KAC', 'Kuwait Airways', 'Kuwaiti','vatsim','Y'),
(381, 'KAJ', 'Karthago Airlines', 'Karthago','vatsim','Y'),
(382, 'KAL', 'Korean Air', 'Korean Air','vatsim','Y'),
(383, 'KAM', 'Karim Airlines', '','vatsim','Y'),
(384, 'KAP', 'Cape Air', 'Cair','vatsim','Y'),
(385, 'KBA', 'Kenn Borek Air', 'Borek Air','vatsim','Y'),
(386, 'KFA', 'Kelowna Flightcraft', 'Flightcraft','vatsim','Y'),
(387, 'KHC', 'Kitty Hawk Airways', 'Cargo Hawk','vatsim','Y'),
(388, 'KIS', 'Contact Air', 'Contactair','vatsim','Y'),
(389, 'KJC', 'Krasair', 'Krasnojarsky Air','vatsim','Y'),
(390, 'KKK', 'Atlasjet International Airways', 'AtlasJet','vatsim','Y'),
(391, 'KLC', 'KLM Cityhopper', 'City','vatsim','Y'),
(392, 'KLM', 'KLM', 'KLM','vatsim','Y'),
(393, 'KNT', 'Knightair', 'Knight','vatsim','Y'),
(394, 'KQA', 'Kenya Airways Ltd', 'Kenya','vatsim','Y'),
(395, 'KRP', 'Carpatair', 'Carpatair','vatsim','Y'),
(396, 'KYV', 'Cyprus Turkish Airlines (KTHY)', 'AirKibris','vatsim','Y'),
(397, 'KZR', 'Air Astana', 'Astanaline','vatsim','Y'),
(398, 'KZW', 'Khalifa Airways', 'Khalifa Air','vatsim','Y'),
(399, 'LAI', 'IAACA', 'Lai','vatsim','Y'),
(400, 'LAJ', 'British Mediterranean Airways', 'Bee Med','vatsim','Y'),
(401, 'LAL', 'Labrador Airways', 'Lab Air','vatsim','Y'),
(402, 'LAM', 'Linhas A?reas de Mo?ambique', 'Mozambique ','vatsim','Y'),
(403, 'LAN', 'LAN Chile', 'LAN','vatsim','Y'),
(404, 'LBT', 'Nouvelair Tunisie', 'Nouvelair','vatsim','Y'),
(405, 'LDA', 'Lauda Air', 'Lauda','vatsim','Y'),
(406, 'LER', 'Laser Airlines', 'Laser','vatsim','Y'),
(407, 'LGD', 'Legend Airlines', 'Legendary','vatsim','Y'),
(408, 'LGL', 'Luxair', 'Luxair','vatsim','Y'),
(409, 'LGR', 'Lesvos Airclub Group', '','vatsim','Y'),
(410, 'LGW', 'LGW', 'Walter','vatsim','Y'),
(411, 'LHA', 'Leipzig Air', 'Leipzig Air','vatsim','Y'),
(412, 'LHT', 'Lufthansa Technik', 'Lufthansa Technik','vatsim','Y'),
(413, 'LIA', 'LIAT', 'Liat','vatsim','Y'),
(414, 'LIL', 'Lithuanian Airlines', 'Lithuanian Air','vatsim','Y'),
(415, 'LIT', 'Air Littoral', 'Air Littoral','vatsim','Y'),
(416, 'LLB', 'Lloyd Aereo Boliviano', 'Boliviano','vatsim','Y'),
(417, 'LNI', 'Lion Airlines', 'Lion Inter','vatsim','Y'),
(418, 'LOG', 'Loganair', 'Logan','vatsim','Y'),
(419, 'LOT', 'LOT', 'Lot','vatsim','Y'),
(420, 'LPE', 'LAN Peru', 'Linea Peru','vatsim','Y'),
(421, 'LPV', 'Air Alps', 'Air Alps','vatsim','Y'),
(422, 'LRC', 'LACSA', 'LACSA','vatsim','Y'),
(423, 'LTA', 'Aerotuy', 'Aerotuy','vatsim','Y'),
(424, 'LTU', 'LTU International Airways', 'LTU','vatsim','Y'),
(425, 'LVG', 'Livingston', 'Livingston','vatsim','Y'),
(426, 'LXP', 'LAN Express', 'Lanex','vatsim','Y'),
(427, 'LXR', 'Air Luxor', 'Airluxor','vatsim','Y'),
(428, 'LZB', 'Bulgaria Air', 'Flying Bulgaria','vatsim','Y'),
(429, 'MAH', 'Mal', 'Malev','vatsim','Y'),
(430, 'MAK', 'Macedonian Airlines', 'Makavio','vatsim','Y'),
(431, 'MAS', 'Malaysia', 'Malaysian','vatsim','Y'),
(432, 'MAU', 'Air Mauritius', 'Airmauritius','vatsim','Y'),
(433, 'MCA', 'MidContinent Airlines', 'Midcon','vatsim','Y'),
(434, 'MCS', 'Macedonian Airlines', 'Macedonian','vatsim','Y'),
(435, 'MDA', 'Mandarin Airlines', 'Mandarin','vatsim','Y'),
(436, 'MDG', 'Air Madagascar', 'Air Madagascar','vatsim','Y'),
(437, 'MDN', 'Meridian Airlines', 'Meridian','vatsim','Y'),
(438, 'MDW', 'Midway Airlines', 'Midway','vatsim','Y'),
(439, 'MEA', 'Middle East Airlines', 'Cedar Jet','vatsim','Y'),
(440, 'MEP', 'Midwest Airlines', 'Midex','vatsim','Y'),
(441, 'MES', 'Mesaba Aviation', 'Mesaba','vatsim','Y'),
(442, 'MMZ', 'EuroAtlantic Airways', 'Euroatlantic','vatsim','Y'),
(443, 'MNB', 'MNG Airlines', 'Blacksea ','vatsim','Y'),
(444, 'SEJ', 'SpiceJet', 'Spicejet','vatsim','Y'),
(445, 'MON', 'Monarch Airlines', 'Monarch','vatsim','Y'),
(446, 'MPD', 'Air Comet', 'Red Comet','vatsim','Y'),
(447, 'MPE', 'Canadian North', 'Empress','vatsim','Y'),
(448, 'MPH', 'Martinair Holland', 'Martinair','vatsim','Y'),
(449, 'MRT', 'alMIRATH', 'Al Mirath','vatsim','Y'),
(450, 'MSR', 'Egyptair', 'Egypt','vatsim','Y'),
(451, 'MTN', 'Mountain Air Virtual', 'Mountain','vatsim','Y'),
(452, 'MVD', 'Kavminvodyavia', 'Air Minvody','vatsim','Y'),
(453, 'MVS', 'MVS Virtual Airlines', 'MAN','vatsim','Y'),
(454, 'MXA', 'Mexicana', 'Mexicana','vatsim','Y'),
(455, 'MXJ', 'MAXjet Airways', 'Maxjet','vatsim','Y'),
(456, 'MYL', 'My Travel Lite', 'Kestral','vatsim','Y'),
(457, 'MYT', 'MyTravel Airways', 'Kestrel','vatsim','Y'),
(458, 'NAO', 'North American Airlines', 'North American','vatsim','Y'),
(459, 'NAX', 'Norwegian Air Shuttle', 'Nor Shuttle','vatsim','Y'),
(460, 'NBL', 'Noble Air', 'Noble','vatsim','Y'),
(461, 'NCA', 'Nippon Cargo Airlines', 'Nippon Cargo','vatsim','Y'),
(462, 'NCB', 'North Cariboo Flying Service', 'North Caribou','vatsim','Y'),
(463, 'NDC', 'FlyNordic', 'Nordic','vatsim','Y'),
(464, 'NEG', 'Night Eagles', 'NightEagle','vatsim','Y'),
(465, 'NGA', 'North German Airlines', '','vatsim','Y'),
(466, 'NJE', 'Netjets', 'Fraction','vatsim','Y'),
(467, 'NJT', 'Netjets International', 'Netjet','vatsim','Y'),
(468, 'NKS', 'Spirit Airlines', 'Spirit Wings','vatsim','Y'),
(469, 'NLY', 'flyniki', 'Flyniki','vatsim','Y'),
(470, 'NMB', 'Air Namibia', 'Namibia','vatsim','Y'),
(471, 'NMH', 'Metro Helicopters', 'Metro','vatsim','Y'),
(472, 'NOR', 'Nordic Air', 'Nordic','vatsim','Y'),
(473, 'NOS', 'Neos', 'Moon Flower','vatsim','Y'),
(474, 'NPI', 'Notas Airlines', 'Notas','vatsim','Y'),
(475, 'NPV', 'Napulevola', '','vatsim','Y'),
(476, 'NRD', 'Nordic Regional - Nordic Leisure', 'Northrider','vatsim','Y'),
(477, 'NSE', 'Satena', 'Satena','vatsim','Y'),
(478, 'NTL', 'Air National Corporate', '','vatsim','Y'),
(479, 'NTR', 'TNT International Aviation', 'Nitro','vatsim','Y'),
(480, 'NTW', 'Nationwide Airlines', 'Nationwide','vatsim','Y'),
(481, 'NVC', 'NavCanada', 'Nav Can','vatsim','Y'),
(482, 'NWA', 'Northwest Airlines', 'Northwest','vatsim','Y'),
(483, 'NYA', 'New York Air', 'Apple','vatsim','Y'),
(484, 'NZA', 'Ansett New Zealand', 'Ansett New Zealand','vatsim','Y'),
(485, 'OAL', 'Olympic Airways', 'Olympic','vatsim','Y'),
(486, 'OAV', 'OMNI Aviation', 'Omni','vatsim','Y'),
(487, 'OAW', 'Helvetic Airways', 'Helvetic','vatsim','Y'),
(488, 'OCA', 'ASERCA', 'Aserca','vatsim','Y'),
(489, 'OGE', 'AtlasJet International', 'AtlasJet','vatsim','Y'),
(490, 'OHK', 'Oasis Hong Kong Airlines', 'Oasis','vatsim','Y'),
(491, 'OHY', 'Onur Airlines', 'OnurAir ','vatsim','Y'),
(492, 'ONE', 'OceanAir', 'Oceanair','vatsim','Y'),
(493, 'ONU', 'Nations Unies Virtuelle', 'www.nuv-fs.net','vatsim','Y'),
(494, 'ONY', 'Onyx Airways', 'Orange','vatsim','Y'),
(495, 'OOM', 'Zoom Airlines', 'Zoom','vatsim','Y'),
(496, 'OPT', 'Flight Options', 'Options','vatsim','Y'),
(497, 'OTA', 'Oita Travel Airlines', '','vatsim','Y'),
(498, 'PAA', 'PanAm', 'Clipper','vatsim','Y'),
(499, 'PAC', 'Polar Air Cargo', 'Polar','vatsim','Y'),
(500, 'PAG', 'Perimeter Aviation', 'Perimeter','vatsim','Y'),
(501, 'PAL', 'Philippine Airlines', 'Philippine','vatsim','Y'),
(502, 'PAY', 'Pacific Airways', 'Pacific','vatsim','Y'),
(503, 'PBA', 'PBair', 'PEEBEE AIR','vatsim','Y'),
(504, 'PCE', 'Pace Airlines', 'Pace','vatsim','Y'),
(505, 'PCO', 'Pacific Coastal Airlines', 'Pasco','vatsim','Y'),
(506, 'PDT', 'USAir Express', 'Piedmont','vatsim','Y'),
(507, 'PGA', 'Portugalia Airlines (PGA)', 'Portugalia','vatsim','Y'),
(508, 'PGT', 'Pegasus', 'Sunturk','vatsim','Y'),
(509, 'PIA', 'Pakistan International Airlines', 'Pakistan','vatsim','Y'),
(510, 'PLK', 'Pulkovo Aviation Enterprise', 'Pulkovo','vatsim','Y'),
(511, 'PNX', 'Phoenix (Virtual) Flight Services', 'Phoenix','vatsim','Y'),
(512, 'PRV', 'Prevair VA', 'Prevair','vatsim','Y'),
(513, 'PRY', 'Privat-Air', 'Privat Air','vatsim','Y'),
(514, 'PTI', 'Privatair SA', 'Privatair','vatsim','Y'),
(515, 'PVI', 'Premium Virtual Airlines', 'Premium','vatsim','Y'),
(516, 'QFA', 'Qantas Airways', 'Qantas','vatsim','Y'),
(517, 'QTR', 'Qatar Airways', 'Qatari','vatsim','Y'),
(518, 'QVA', 'Qantas Virtual Airways', '','vatsim','Y'),
(519, 'RAA', 'Royale Airlines', 'Royale','vatsim','Y'),
(520, 'RAM', 'Royal Air Maroc', 'Airmaroc','vatsim','Y'),
(521, 'RBA', 'Royal Brunei Airlines', 'Brunei','vatsim','Y'),
(522, 'REA', 'Aer Arann', 'Aer Arann','vatsim','Y'),
(523, 'REP', 'Republic Airlines', 'Republic','vatsim','Y'),
(524, 'REU', 'Air Austral', 'Reunion','vatsim','Y'),
(525, 'RIV', 'Riviera Airlines', 'Riviera','vatsim','Y'),
(526, 'RJA', 'Royal Jordanian Airlines', 'Royal Jordanian','vatsim','Y'),
(527, 'RKA', 'Air Afrique', 'Airafric','vatsim','Y'),
(528, 'RNA', 'Royal Nepal Airlines', 'Royal Nepal','vatsim','Y'),
(529, 'ROI', 'Avior Airlines', 'Avior','vatsim','Y'),
(530, 'ROJ', 'Royal Jet', 'Royal Jet','vatsim','Y'),
(531, 'ROT', 'TAROM', 'Tarom','vatsim','Y'),
(532, 'ROY', 'Royal Airlines', 'Roy','vatsim','Y'),
(533, 'RPB', 'Aero Republica', 'Aerorepublica','vatsim','Y'),
(534, 'RPX', 'BAC Express', 'Rapex','vatsim','Y'),
(535, 'RSL', 'Rio Sul', 'Riossul','vatsim','Y'),
(536, 'RUS', 'Cirrus Airlines', 'Cirrus','vatsim','Y'),
(537, 'RYR', 'Ryanair', 'Ryanair','vatsim','Y'),
(538, 'RZO', 'SATA International', 'Air Azores','vatsim','Y'),
(539, 'SAA', 'South African Airways', 'Springbock','vatsim','Y'),
(540, 'SAB', 'Sabena Belgian Airways', 'Sabena','vatsim','Y'),
(541, 'SAC', 'Simulated Air Canada', 'Air Canada','vatsim','Y'),
(542, 'SAM', 'SAM Colombia', 'Sam','vatsim','Y'),
(543, 'SAS', 'SAS', 'Scandinavian','vatsim','Y'),
(544, 'SAT', 'SATA Air A?ores', 'SATA','vatsim','Y'),
(545, 'SAW', 'Seaway Airlines', '','vatsim','Y'),
(546, 'SAY', 'ScotAirways', 'Suckling','vatsim','Y'),
(547, 'SBI', 'S7 Airlines', 'Siberian Airlines','vatsim','Y'),
(548, 'SCW', 'Malm? Aviation', 'Scanwings','vatsim','Y'),
(549, 'SCX', 'Sun Country Airlines', 'Sun Country','vatsim','Y'),
(550, 'SCY', 'Air Scandic', 'Airscan','vatsim','Y'),
(551, 'SER', 'Aero California', 'Aerocalifornia','vatsim','Y'),
(552, 'SEU', 'Star Airlines', 'Starway','vatsim','Y'),
(553, 'SEY', 'Air Seychelles', 'Seychelles','vatsim','Y'),
(554, 'SFV', 'Smile and Fly', '','vatsim','Y'),
(555, 'SHT', 'British Airways Shuttle', 'Shuttle','vatsim','Y'),
(556, 'SHY', 'Sky Airlines', 'Antalya Bird','vatsim','Y'),
(557, 'SIA', 'Singapore Airlines', 'Singapore','vatsim','Y'),
(558, 'SIH', 'Skynet Airlines', 'Bluejet','vatsim','Y'),
(559, 'SKG', 'Skyward Aviation', 'Skyward','vatsim','Y'),
(560, 'SKV', 'Skyways', '','vatsim','Y'),
(561, 'SKW', 'SkyWest Airlines', 'Skywest','vatsim','Y'),
(562, 'SKX', 'Skyways', 'Sky Express','vatsim','Y'),
(563, 'SKY', 'Skymark Airlines', 'Skymark','vatsim','Y'),
(564, 'SLI', 'Aerolitoral', 'Costera','vatsim','Y'),
(565, 'SLK', 'SilkAir', 'Silkair','vatsim','Y'),
(566, 'SLM', 'Surinam Airways', 'Surinam','vatsim','Y'),
(567, 'SNB', 'Sterling European Airways', 'Sterling','vatsim','Y'),
(568, 'SNG', 'Air S?n?gal', 'Senegal Inter','vatsim','Y'),
(569, 'SNU', 'SouthAmerican', 'turpial','vatsim','Y'),
(570, 'SOA', 'Southern Airways', 'Southern','vatsim','Y'),
(571, 'SOC', 'SOCAIR VA', 'Socair','vatsim','Y'),
(572, 'SPM', 'Air Saint-Pierre', 'Saint-Pierre','vatsim','Y'),
(573, 'SQC', 'Singapore Airlines Cargo', 'Singcargo','vatsim','Y'),
(574, 'SSV', 'Skyservice Airlines', 'Skytours','vatsim','Y'),
(575, 'STF', 'Starflight', 'Starflight','vatsim','Y'),
(576, 'STV', 'Stevens Virtual Airlines', 'Stevens','vatsim','Y'),
(577, 'STY', 'Styrian Airways', 'Styrian','vatsim','Y'),
(578, 'SUR', 'SUR Air System', 'Sur','vatsim','Y'),
(579, 'SVA', 'Saudi Arabian Airlines', 'Saudia','vatsim','Y'),
(580, 'SVK', 'Air Slovakia', 'Slovakia','vatsim','Y'),
(581, 'SVR', 'Ural Airlines', 'Sverdlovsk Air','vatsim','Y'),
(582, 'SWA', 'Southwest Airlines', 'Southwest','vatsim','Y'),
(583, 'SWD', 'Southern Winds', 'Southern Winds','vatsim','Y'),
(584, 'SWN', 'West Air Sweden', 'Air Sweden','vatsim','Y'),
(585, 'SWR', 'Swiss Airlines', 'Swiss','vatsim','Y'),
(586, 'SWV', 'Swe Fly', 'Flying Swede','vatsim','Y'),
(587, 'SXS', 'SunExpress Airlines', 'SunExpress ','vatsim','Y'),
(588, 'TAE', 'TAME', 'Tame','vatsim','Y'),
(589, 'TAM', 'TAM Brazil', 'TAM','vatsim','Y'),
(590, 'TAP', 'TAP', 'Air Portugal','vatsim','Y'),
(591, 'TAR', 'Tunisair', 'Tunisair','vatsim','Y'),
(592, 'TCA', 'Tradewind Caribbean Airlines', 'Tradewind','vatsim','Y'),
(593, 'TCV', 'TACV', 'Caboverbe','vatsim','Y'),
(594, 'TCW', 'Thomas Cook Airlines Belgium', 'Thomas Cook','vatsim','Y'),
(595, 'TCX', 'Thomas Cook Airlines', 'Kestrel','vatsim','Y'),
(596, 'TFF', 'The Flying Friends', 'Friendship','vatsim','Y'),
(597, 'TFL', 'Arkefly', 'Arkefly','vatsim','Y'),
(598, 'TGV', 'Thai Airways Virtual', '','vatsim','Y'),
(599, 'TGW', 'Tiger Airways', 'Go Cat','vatsim','Y'),
(600, 'TGZ', 'Airzena Georgian Airlines', 'Tamazi','vatsim','Y'),
(601, 'THA', 'Thai Airways', 'Thai','vatsim','Y'),
(602, 'THT', 'Air Tahiti Nui', 'Tahiti Airlines','vatsim','Y'),
(603, 'THY', 'Turkish Airlines', 'Turk Air','vatsim','Y'),
(604, 'TIV', 'Texas International Airlines', 'Texas','vatsim','Y'),
(605, 'TKC', 'Turkish Cargo Virtual', 'Cargoturk','vatsim','Y'),
(606, 'TOM', 'Thomsonfly', 'Thomson','vatsim','Y'),
(607, 'TPA', 'Tampa Cargo', 'Tampa','vatsim','Y'),
(608, 'TPR', 'Transpolar Virtual Airline', 'Transpolar','vatsim','Y'),
(609, 'TRA', 'Transavia Airlines', 'Transavia','vatsim','Y'),
(610, 'TRS', 'AirTran Airways', 'Citrus','vatsim','Y'),
(611, 'TSC', 'Air Transat', 'Transat','vatsim','Y'),
(612, 'TSO', 'Transaero Airlines', 'Transoviet','vatsim','Y'),
(613, 'TTL', 'Total Linhas Aereas', 'Total','vatsim','Y'),
(614, 'TVS', 'Travel Service', 'Skytravel','vatsim','Y'),
(615, 'TWA', 'Trans World Airlines', 'TWA','vatsim','Y'),
(616, 'TYR', 'Tyrolean Airways', 'Tyrolean','vatsim','Y'),
(617, 'UAA', 'United African Airways', '','vatsim','Y'),
(618, 'UAE', 'Emirates', 'Emirates','vatsim','Y'),
(619, 'UAL', 'United Airlines', 'United','vatsim','Y'),
(620, 'UAS', 'Universal Air Service', 'Universal','vatsim','Y'),
(621, 'UIA', 'UNI Airways', 'Glory','vatsim','Y'),
(622, 'UKD', 'UK Direct Airways', 'Unicorn','vatsim','Y'),
(623, 'UKR', 'Air Ukraine', 'Air Ukraine','vatsim','Y'),
(624, 'ULA', 'Zuliana de Aviacion', 'zuliana','vatsim','Y'),
(625, 'UPS', 'United Parcel Service', 'UPS','vatsim','Y'),
(626, 'USA', 'US Airways', 'Cactus','vatsim','Y'),
(627, 'UTY', 'Alliance Airlines', 'Unity','vatsim','Y'),
(628, 'UYC', 'Cameroon Airlines', 'Cam-Air ','vatsim','Y'),
(629, 'UZB', 'Uzbekistan Airways', 'Uzbek','vatsim','Y'),
(630, 'VAF', 'Virtual Air France', '','vatsim','Y'),
(631, 'VAR', 'VirtuAliRoma', 'VirtuAliRoma','vatsim','Y'),
(632, 'VAZ', 'VirtuAlitalia', '','vatsim','Y'),
(633, 'VBA', 'V Bird', 'VeeBee','vatsim','Y'),
(634, 'VBW', 'Air Burkina', 'Burkina','vatsim','Y'),
(635, 'VBX', 'Virtual Coast Air', 'Coast','vatsim','Y'),
(636, 'VDA', 'Volga Dnepr', 'Volga-Dnepr','vatsim','Y'),
(637, 'VDB', 'Virtual BritAir', '','vatsim','Y'),
(638, 'VEX', 'Virgin Express', 'Virgin Express','vatsim','Y'),
(639, 'VGN', 'Virgin Nigeria Airways', 'Virgin Nigeria','vatsim','Y'),
(640, 'VIA', 'VIASA', 'Viasa','vatsim','Y'),
(641, 'VIR', 'Virgin Atlantic Airways', 'Virgin','vatsim','Y'),
(642, 'VIX', 'Vixair', '','vatsim','Y'),
(643, 'VJA', 'ValueJet', ' ','vatsim','Y'),
(644, 'VKG', 'Thomas Cook Scandinavia', 'Viking','vatsim','Y'),
(645, 'VLE', 'Volare Airlines', 'Revola','vatsim','Y'),
(646, 'VLG', 'Vueling Airlines', 'Vueling','vatsim','Y'),
(647, 'VLK', 'Vladivostok Avia', 'Vladair','vatsim','Y'),
(648, 'VLM', 'VLM Airlines', 'Rubens','vatsim','Y'),
(649, 'VOZ', 'Virgin Australia', 'Virgin','vatsim','Y'),
(650, 'VQG', 'The Virtual Qualiflyer Group', '','vatsim','Y'),
(651, 'VRG', 'VARIG', 'Varig','vatsim','Y'),
(652, 'VSP', 'VASP Viacao Aerea Sao Paulo', 'VASP','vatsim','Y'),
(653, 'VSW', 'Virtual Skyways', 'Skyways','vatsim','Y'),
(654, 'VUK', 'Virtual Uk-Airlines', 'Airbird','vatsim','Y'),
(655, 'VUN', 'Air Ivoire', 'Airvoire ','vatsim','Y'),
(656, 'VUS', 'Virgin America Airways', '','vatsim','Y'),
(657, 'WAL', 'Western Airlines', 'Western','vatsim','Y'),
(658, 'WAW', 'World Airways', 'Wings','vatsim','Y'),
(659, 'WCA', 'West Coast Air', 'Coast Air','vatsim','Y'),
(660, 'WDA', 'Wardair Canada', 'Wardair','vatsim','Y'),
(661, 'WEA', 'White Eagle Avation Virtual Airlines', 'White Eagle','vatsim','Y'),
(662, 'WES', 'Western Express', 'Westex','vatsim','Y'),
(663, 'WFD', 'BAe Systems', 'Phoenix','vatsim','Y'),
(664, 'WHT', 'White Airways', 'Whitejet','vatsim','Y'),
(665, 'WIF', 'Wider?e', 'Wideroe','vatsim','Y'),
(666, 'WJA', 'Westjet Airlines', '','vatsim','Y'),
(667, 'WLC', 'Welcome Air', 'Welcomeair','vatsim','Y'),
(668, 'WOA', 'World Airways', 'World','vatsim','Y'),
(669, 'WOW', 'Air Southwest', 'Swallow','vatsim','Y'),
(670, 'WSG', 'Wasaya Airways', 'Wasaya','vatsim','Y'),
(671, 'WTA', 'World Travel Airline', 'Travelair','vatsim','Y'),
(672, 'WWA', 'Westwind Airlines', 'WestWind','vatsim','Y'),
(673, 'WZP', 'Zip Air', 'Windzip','vatsim','Y'),
(674, 'WZZ', 'Wizz Air', 'Wizz Air','vatsim','Y'),
(675, 'BCI', 'Blue Islands', 'Blue Island','vatsim','Y'),
(676, 'XLA', 'Excel Airways', 'Expo','vatsim','Y'),
(677, 'XNA', 'Express Net Airlines', 'Expressnet','vatsim','Y'),
(678, 'YMA', 'Compass Airlines', 'Compass','vatsim','Y'),
(679, 'ZIW', 'WestAir', '','vatsim','Y'),
(680, 'ZOA', 'Oakland ARTCC Fleet', 'Oakland','vatsim','Y'),
(681, 'ZVA', 'Zenavia', '','vatsim','Y'),
(682, 'CHO', 'Flugrettung', 'Christopherus','vatsim','Y'),
(683, 'CHR', 'Luftrettung', 'Christoph','vatsim','Y'),
(684, 'AFP', 'Portugese Airforce', '','vatsim','Y'),
(685, 'AME', 'Spanish Airforce', 'Airmil','vatsim','Y'),
(686, 'CWL', 'RAF Cranwell Training', '','vatsim','Y'),
(687, 'ARN', 'Aeroregional de Antioquia', 'Aeroregional','vatsim','Y'),
(688, 'ASY', 'Royal Australian Air Force', 'Aussie','vatsim','Y'),
(689, 'BAF', 'Belgian Airforce', 'Belgian Airforce','vatsim','Y'),
(690, 'CAF', 'Chinese Air Force (TAIWAN)', '','vatsim','Y'),
(691, 'CEF', 'Czech Airforce', '','vatsim','Y'),
(692, 'CFC', 'Canadian Armed Forces', 'Canforce','vatsim','Y'),
(693, 'DAF', 'Danish Airforce', 'Danish Airforce','vatsim','Y'),
(694, 'FAA', 'Argentina Air Force', '','vatsim','Y'),
(695, 'FAB', 'Brazilian Air Force', '','vatsim','Y'),
(696, 'FAF', 'French Airforce', 'French Airforce','vatsim','Y'),
(697, 'FAG', 'Argentine Air Force', '','vatsim','Y'),
(698, 'FNF', 'Finnish Airforce', 'Finnforce','vatsim','Y'),
(699, 'FPR', 'Peruvian Air Force', '','vatsim','Y'),
(700, 'GAF', 'German Airforce', 'German Airforce','vatsim','Y'),
(701, 'HAF', 'Hellenic Air Force', 'Hellenic Air Force','vatsim','Y'),
(702, 'HRZ', 'Croatian Air Force', 'Croatian Airforce','vatsim','Y'),
(703, 'IAF', 'Israel Air Force', 'Israel Air Force','vatsim','Y'),
(704, 'ICG', 'Icelandic Coast Guard', 'Iceland Coast','vatsim','Y'),
(705, 'IRL', 'Irish Air Corps', 'Irish','vatsim','Y'),
(706, 'ITF', 'Italian Air Force', '','vatsim','Y'),
(707, 'KIW', 'Royal New Zealand Air Force', 'Kiwi','vatsim','Y'),
(708, 'MAB', 'Brazilian Navy', '','vatsim','Y'),
(709, 'NAF', 'Royal Netherlands Airforce', 'Netherlands Airforce','vatsim','Y'),
(710, 'NOW', 'Royal Norwegian Airforce', 'Norwegian','vatsim','Y'),
(711, 'NRN', 'Royal Netherlands Navy', 'Netherlands Navy','vatsim','Y'),
(712, 'NVY', 'Royal Navy UK', 'Navy','vatsim','Y'),
(713, 'PLF', 'Polish Airforce', 'Polish Airforce','vatsim','Y'),
(714, 'RAF', 'Royal Airforce UK', '','vatsim','Y'),
(715, 'RFF', 'Russian Federation Air Force', 'Russian Air Force','vatsim','Y'),
(716, 'RFR', 'Royal Airforce UK', 'Rafair','vatsim','Y'),
(717, 'ROF', 'Romanian Air Force', '','vatsim','Y'),
(718, 'RRR', 'Royal Airforce UK', 'Ascot','vatsim','Y'),
(719, 'SUI', 'Swiss Airforce', 'Airforce Switzerland','vatsim','Y'),
(720, 'SVF', 'Swedish Armed Forces', 'Sweedforce','vatsim','Y'),
(721, 'THK', 'T?rk Hava Kuvvetleri', 'Turkish Air Force (TUAF)','vatsim','Y'),
(722, 'MET', 'MetroAir', 'Metro','vatsim','Y'),
(723, 'VRD', 'Virgin America', 'Redwood','vatsim','Y'),
(724, 'A', 'US Air Force', 'Air Force','vatsim','Y'),
(725, 'ZSE', 'Seattle Artcc Fleet', 'Seawhawk','vatsim','Y'),
(726, 'PUA', 'PLUNA', 'Pluna','vatsim','Y'),
(727, 'CAX', 'California Airlines', 'Cal Air','vatsim','Y'),
(728, 'DRD', 'Dardanelair', '','vatsim','Y'),
(729, 'KRD', 'Karadeniz', '','vatsim','Y'),
(730, 'QXE', 'Horizon Air', 'Horizon','vatsim','Y'),
(731, 'PUG', 'RallyeAir ', 'Rallyeair','vatsim','Y'),
(732, 'SEA', 'SkyEast', '','vatsim','Y'),
(733, 'EFV', 'euflyVirtual', 'EUFLY','vatsim','Y'),
(734, 'CSB', 'Cassubian Airways', 'Cassubian','vatsim','Y'),
(735, 'VAT', 'VATBRASIL', '','vatsim','Y'),
(736, 'GLO', 'Gol', 'GOL','vatsim','Y'),
(737, 'LNE', 'LAN Ecuador', 'LAN ECUADOR','vatsim','Y'),
(738, 'VFA', 'FastAir', '','vatsim','Y'),
(739, 'TAI', 'TACA', 'TACA','vatsim','Y'),
(740, 'PWA', 'Pacific West Airways', 'Pacific West','vatsim','Y'),
(741, 'HHA', 'Atlantic Honduras', 'Atlantic Honduras','vatsim','Y'),
(742, 'SHM', 'Shhakkim', 'Shhakkim','vatsim','Y'),
(743, 'IZ', 'Arkia Israeli', 'Arkia','vatsim','Y'),
(744, 'JGN', 'Guinness Airline', '','vatsim','Y'),
(745, 'WPC', 'Westport Virtual Charters', '','vatsim','Y'),
(746, 'PBN', 'Pacific Blue Airlines', 'Bluebird','vatsim','Y'),
(747, 'SAX', 'SunAir Express', '','vatsim','Y'),
(748, 'PDX', 'Portland Air', 'Portland','vatsim','Y'),
(749, 'CAT', 'Catalonian Airlines', 'Catalonian','vatsim','Y'),
(750, 'FRIESE', 'Friesen-Flieger', '','vatsim','Y'),
(751, 'SIB', 'Sibaviatrans', 'Sibavia','vatsim','Y'),
(752, 'ASV', 'Atlantic Sun Airways', 'Atlantic Sun','vatsim','Y'),
(753, 'TAY', 'TNT Airways', 'Quality','vatsim','Y'),
(754, 'RLK', 'Air Nelson', 'Link','vatsim','Y'),
(755, 'EAG', 'Eagle Airways', 'Eagle','vatsim','Y'),
(756, 'NZM', 'Mount Cook Airline', 'Mount Cook','vatsim','Y'),
(757, 'RNV', 'Armavia', 'Armavia','vatsim','Y'),
(758, 'ZIN', 'Air International', '','vatsim','Y'),
(759, 'CFE', 'BA CityFlyer', 'Flyer','vatsim','Y'),
(760, 'WDY', 'Chicago Express', 'Windy City','vatsim','Y'),
(761, 'AZT', 'Aztec Airlines', '','vatsim','Y'),
(762, 'SLE', 'Sky Line Virtual', '','vatsim','Y'),
(763, 'NAVAL', 'Chilean Navy', '','vatsim','Y'),
(764, 'FACH', 'Chilean Air Force', '','vatsim','Y'),
(765, 'E', 'Chilean Army', '','vatsim','Y'),
(766, 'MQT', 'Air ITM', 'Musketeer','vatsim','Y'),
(767, 'JJN', 'Japan Jet Network', 'Network','vatsim','Y'),
(768, 'SWG', 'Sunwing Airlines', 'Sunwing','vatsim','Y'),
(769, 'AMQ', 'Aeromedicare', 'Lifeline','vatsim','Y'),
(770, 'ANG', 'Air Niugini', 'Niugini','vatsim','Y'),
(771, 'RXA', 'Regional Express', 'Rex','vatsim','Y'),
(772, 'JAG', 'JetAlliance', 'Jetalliance','vatsim','Y'),
(773, 'XLI', 'XlineVA', '','vatsim','Y'),
(774, 'APF', 'Amapola Flyg', 'Amapola','vatsim','Y'),
(775, 'NVR', 'Novair', 'Navigator','vatsim','Y'),
(776, 'MRH', 'RAF Marham Training', '','vatsim','Y'),
(777, 'SYS', 'RAF Shawbury Training', '','vatsim','Y'),
(778, 'SRG', 'RAF Search & Rescue', '','vatsim','Y'),
(779, 'BKH', 'RAF Barkston Heath Training', '','vatsim','Y'),
(780, 'VLL', 'RAF Valley Training', '','vatsim','Y'),
(781, 'LOP', 'RAF Linton-on-Ouse Training', '','vatsim','Y'),
(782, 'VTA', 'Air Tahiti', 'Air Tahiti','vatsim','Y'),
(783, 'WIA', 'Winair', 'Windward','vatsim','Y'),
(784, 'CMF', 'Air Care Alliance', 'Compassion','vatsim','Y'),
(785, 'BMJ', 'Bemidji Airlines', 'Bemidji','vatsim','Y'),
(786, 'MAX', 'MaxFreight', 'Max','vatsim','Y'),
(787, 'FWL', 'Florida West', 'Flo West','vatsim','Y'),
(788, 'GHB', 'Ghana International', 'Ghana Airlines','vatsim','Y'),
(789, 'GOE', 'Go Fly', '','vatsim','Y'),
(790, 'GJS', 'GoJet Airlines', 'Lindbergh','vatsim','Y'),
(791, 'DVC', 'Deer Valley Flying Club', 'Deer Valley','vatsim','Y'),
(792, 'OZJ', 'OzJet Airlines', 'Ozjet','vatsim','Y'),
(793, 'KNI', 'KD Avia', 'Kalinigrad Air','vatsim','Y'),
(794, 'DOJ', 'US Dept of Justice', 'Justice','vatsim','Y'),
(795, 'ABV', 'Alpha Blue', 'Alpha Blue','vatsim','Y'),
(796, 'FRL', 'Freedom Airlines', 'Freedom Air','vatsim','Y'),
(797, 'JUS', 'USA Jet', 'USA Jet','vatsim','Y'),
(798, 'NRG', 'US Dept of Energy', 'Energy','vatsim','Y'),
(799, 'AAY', 'Allegiant Air', 'Allegiant','vatsim','Y'),
(800, 'KIL', 'Kuban Airlines', 'Air Kuban','vatsim','Y'),
(801, 'BON', 'B&H Airlines', 'Air Bosna','vatsim','Y'),
(802, 'BSK', 'Miami Air', 'Biscayne','vatsim','Y'),
(803, 'JJA', 'Jeju Air', 'Jejuair','vatsim','Y'),
(804, 'ELK', 'ELK Airways', 'Elka','vatsim','Y'),
(805, 'POE', 'Porter Airlines', 'Porter Air','vatsim','Y'),
(806, 'TOW', 'Tower Air', 'Tee Air','vatsim','Y'),
(807, 'GZP', 'Gazpromavia', 'Gazprom','vatsim','Y'),
(808, 'GLA', 'Great Lakes Airlines', 'Lakes Air','vatsim','Y'),
(809, 'RPA', 'Republic Airlines', 'Brickyard','vatsim','Y'),
(810, 'TCF', 'Shuttle America', 'Mercury','vatsim','Y'),
(811, 'SDM', 'Rossiya', 'Russia','vatsim','Y'),
(812, 'ATL', 'Atl?ntica Brasil', 'Atl?ntica','vatsim','Y'),
(813, 'VIP', 'Virtual Pilots Association', 'Freewings','vatsim','Y'),
(814, 'ALC', 'Allied Air Cargo', 'Allied','vatsim','Y'),
(815, 'FAT', 'Farnair Switzerland', 'Farner','vatsim','Y'),
(816, 'FAH', 'Farnair Hungary', 'Blue Strip','vatsim','Y'),
(817, 'XAX', 'AirAsia X', 'Xanadu','vatsim','Y'),
(818, 'ARB', 'Arabian Airlines', 'Arabian','vatsim','Y'),
(819, 'CAY', 'Cayman Airways', 'Cayman','vatsim','Y'),
(820, 'CVC', 'Centre-Avia', 'Aviacentre','vatsim','Y'),
(821, 'FSA', 'FSAviator', 'FSAviator','vatsim','Y'),
(822, 'MAV', 'Matsakoni Airlines Virtual', 'Matsakoni','vatsim','Y'),
(823, 'AMV', 'AMC Airlines', 'AMC','vatsim','Y'),
(824, 'LOF', 'Trans States Airlines', 'Waterski','vatsim','Y'),
(825, 'AMU', 'Air Macau', 'Air Macau','vatsim','Y'),
(826, 'HKE', 'Hong Kong Express', 'Hongkong Shuttle','vatsim','Y'),
(827, 'GAR', 'Great Australian Air Rally', '','vatsim','Y'),
(828, 'BRV', 'Breathe Airways', 'Breathe','vatsim','Y'),
(829, 'CPZ', 'Compass Airlines', 'Compass Rose','vatsim','Y'),
(830, 'SKU', 'Sky Airline', 'Aerosky','vatsim','Y'),
(831, 'DLU', 'Air Comet Chile', 'Del Sur','vatsim','Y'),
(832, 'DAP', 'Aerovias DAP', 'DAP','vatsim','Y'),
(833, 'PCP', 'Aerol?neas Principal ', '','vatsim','Y'),
(834, 'SSX', 'Lynx Aviation', 'Shasta','vatsim','Y'),
(835, 'VRN', 'VARIG', 'Varig','vatsim','Y'),
(836, 'MMA', 'Myanmar Airways Intl', '','vatsim','Y'),
(837, 'UBA', 'Myanma Airways', '','vatsim','Y'),
(838, 'ADA', 'Air Dream Airways', 'Air Dream','vatsim','Y'),
(839, 'HAR', 'Hellenic Air', '','vatsim','Y'),
(840, 'SSQ', 'Sunstate Airlines', 'Sunstate','vatsim','Y'),
(841, 'EAQ', 'Eastern Australia Airlines', 'Eastern','vatsim','Y'),
(842, 'NJS', 'National Jet Systems', 'National','vatsim','Y'),
(843, 'BOE', 'Boeing Commercial Airplane Group', 'Boeing','vatsim','Y'),
(844, 'MED', 'Mediterranea Virtual', 'Mediterranea','vatsim','Y'),
(845, 'TSK', 'Tomsk Avia', 'Tomsk Avia','vatsim','Y'),
(846, 'RCH', 'US Air Force AMC', 'Reach','vatsim','Y'),
(847, 'BLU', 'Cerulean Airlines', 'Bluesky','vatsim','Y'),
(848, 'TPU', 'TACA Peru', 'Trans Peru','vatsim','Y'),
(849, 'ICD', 'Icaro Air', 'Icaro','vatsim','Y'),
(850, 'VUR', 'VIP Ecuador', 'VIP','vatsim','Y'),
(851, 'CXP', 'Xtra Airways', 'Casino Express','vatsim','Y'),
(852, 'RYN', 'Ryan International Airlines', 'Ryan International','vatsim','Y'),
(853, 'PHA', 'Phoenix Aviation Group', 'Gray Bird','vatsim','Y'),
(854, 'UKC', 'Cougar Virtual', 'Speedcat','vatsim','Y'),
(855, 'APW', 'Arrow Cargo', 'Big A','vatsim','Y'),
(856, 'SKB', 'Skybus', 'Skybus','vatsim','Y'),
(857, 'MPJ', 'MAP Executive Flightservice', 'Map Jet','vatsim','Y'),
(858, 'AMF', 'Ameriflight', 'Amflight','vatsim','Y'),
(859, 'VVM', 'Viva Macau', 'Jackpot','vatsim','Y'),
(860, 'ALX', 'Hewa Bora Airways', 'All Congo','vatsim','Y'),
(861, 'IFL', 'Interflug', 'Interflug','vatsim','Y'),
(862, 'RTL', 'Rheintalflug', 'Rheintalflug','vatsim','Y'),
(863, 'VOI', 'Volaris', 'Volaris','vatsim','Y'),
(864, 'AIJ', 'Interjet', 'Interjet','vatsim','Y'),
(865, 'WKD', 'Weekendair', 'Weekendair','vatsim','Y'),
(866, 'BLE', 'Blue Line', 'Blue Berry','vatsim','Y'),
(867, 'CG', 'U.S. Coast Guard', 'Coast Guard','vatsim','Y'),
(868, 'KHB', 'Dalavia', 'Dalavia','vatsim','Y'),
(869, 'FPG', 'TAG Aviation', 'TAG Aviation','vatsim','Y'),
(870, 'TAG', 'TAG Aviation USA', 'TAG U-S','vatsim','Y'),
(871, 'CRK', 'Hong Kong Airlines', 'Bauhinia','vatsim','Y'),
(872, 'AJI', 'Ameristar Air Cargo', 'Ameristar','vatsim','Y'),
(873, 'CWC', 'Centurion Air Cargo', 'Challenge Cargo','vatsim','Y'),
(874, 'LAU', 'L?neas A?reas Suramericanas', 'Suramericano','vatsim','Y'),
(875, 'FUS', 'Fusion Airways', 'Riptide','vatsim','Y'),
(876, 'MGX', 'Montenegro Airlines', 'Montair','vatsim','Y'),
(877, 'FBL', 'FlyBlue Airways', 'FlyBlue','vatsim','Y'),
(878, 'RIT', 'Asian Spirit', 'Asian Spirit','vatsim','Y'),
(879, 'CMI', 'Continental Micronesia', 'Air Mike','vatsim','Y'),
(880, 'SHU', 'SAT Airlines', 'Satair','vatsim','Y'),
(881, 'FFP', 'Prima Charter', 'Flying Fish','vatsim','Y'),
(882, 'TUS', 'ABSA Cargo', 'ABSA Cargo','vatsim','Y'),
(883, 'BEL', 'Brussels Airlines', 'Bee-Line','vatsim','Y'),
(884, 'YMF', 'Compass Logistics', 'Compass','vatsim','Y'),
(885, 'IAW', 'Iraqi Airways', 'Iraqi','vatsim','Y'),
(886, 'ZEY', 'DIAS AIR', 'DIAS','vatsim','Y'),
(887, 'JAM', 'Jamaica Airlines', 'Jamair','vatsim','Y'),
(888, 'ATN', 'Air Transport International', 'Air Transport','vatsim','Y'),
(889, 'CCI', 'Capital Cargo', 'Cappy','vatsim','Y'),
(890, 'ANE', 'Air Nostrum', 'Nostrum Air','vatsim','Y'),
(891, 'GES', 'Gestair', 'Gestair','vatsim','Y'),
(892, 'ACS', 'Air Canadian Sun', '','vatsim','Y'),
(893, 'ACC', 'Air Canadian Cargo', '','vatsim','Y'),
(894, 'TLV', 'Team Logistics', 'Team','vatsim','Y'),
(895, 'VIK', 'Viking Airlines', 'Swedjet','vatsim','Y'),
(896, 'EMB', 'Embraer', 'Embraer','vatsim','Y'),
(897, 'KGL', 'Kolavia', 'Kogalym','vatsim','Y'),
(898, 'BOS', 'OpenSkies', 'Mistral','vatsim','Y'),
(899, 'WCP', 'Primaris Airlines', 'Whitecap','vatsim','Y'),
(900, 'SWL', 'Transjet Airways', 'Swing','vatsim','Y'),
(901, 'CIX', '2-4-Cix', 'Cix','vatsim','Y'),
(902, 'SAV', 'Severnair', '','vatsim','Y'),
(903, 'TBA', 'TransBrasil Airlines', 'Transbrasil','vatsim','Y'),
(904, 'USH', 'U.S. Helicopter', 'U.S. Heli','vatsim','Y'),
(905, 'GRPFLT', 'Group Flight', 'Group Flight','vatsim','Y'),
(906, 'PSA', 'Pacific Southwest Airlines', 'PSA','vatsim','Y'),
(907, 'OMA', 'Oman Air', 'Oman Air','vatsim','Y'),
(908, 'BET', 'BETA Cargo', 'Beta Cargo','vatsim','Y'),
(909, 'JAZ', 'JALways', 'Jalways','vatsim','Y'),
(910, 'PHW', 'Jupiter Airlines', '','vatsim','Y'),
(911, 'DJS', 'DayJet', 'Dayjet','vatsim','Y'),
(912, 'OAE', 'Omni Air', 'Omni-Express','vatsim','Y'),
(913, 'CPT', 'Hitit Air', 'Capital','vatsim','Y'),
(914, 'ART', 'AeroTrans', 'AeroTrans','vatsim','Y'),
(915, 'WEB', 'Webjet Linhas A?reas', 'Webjet','vatsim','Y'),
(916, 'RSU', 'Aerosur', 'Aerosur','vatsim','Y'),
(917, 'UKV', 'Fly UK Virtual Airways', 'Skyways','vatsim','Y'),
(918, 'VAU', 'V Australia', 'Vee-Oz','vatsim','Y'),
(919, 'TQV', 'Trans-Qu?bec Virtuel', 'Trans-Qu?bec','vatsim','Y'),
(920, 'FCM', 'Finncomm Airlines', 'Finncomm','vatsim','Y'),
(921, 'GA', 'Global Aviation', 'Global Aviation','vatsim','Y'),
(922, 'LAP', 'TAM Airlines (Paraguay)', 'Paraguaya','vatsim','Y'),
(923, 'OLS', 'Sol L?neas A?reas', 'Sol','vatsim','Y'),
(924, 'ILA', 'Virtual Israel Air-ILA', 'ILA','vatsim','Y'),
(925, 'KNE', 'Nas Air', 'Nas Express','vatsim','Y'),
(926, 'VBJ', 'Virtual Corporate Business Jet', 'Bizjet','vatsim','Y'),
(927, 'XMS', 'British Airways (Santa)', 'Santa','vatsim','Y'),
(928, 'CFV', 'Corporate FlyVirtual Alliance', 'SuperFly','vatsim','Y'),
(929, 'MEG', 'Mega Linhas A?reas Virtual', 'Mega','vatsim','Y'),
(930, 'CBE', 'Mexicana Click', 'Click','vatsim','Y'),
(931, 'TIB', 'TRIP Linhas A?reas', 'Trip','vatsim','Y'),
(932, 'IFA', 'Flight Ambulance Intl', 'Red Angle','vatsim','Y'),
(933, 'PAW', 'Premier Airways', 'Premier','vatsim','Y'),
(934, 'NC', 'North Central Airlines', 'North Central','vatsim','Y'),
(935, 'LLM', 'Yamal Airlines', 'Yamal','vatsim','Y'),
(936, 'TMN', 'UTair', 'Utair','vatsim','Y'),
(937, 'IPG', 'Island Pacific Group', 'Island Pacific','vatsim','Y'),
(938, 'SMY', 'Sama', 'Najim','vatsim','Y'),
(939, 'CCC', 'Canada Charters & Cargo', 'Canada Charters','vatsim','Y'),
(940, 'AKA', 'Alaska Adventures', 'Alaska','vatsim','Y'),
(941, 'ANO', 'Airnorth', 'Topend','vatsim','Y'),
(942, 'DGV', 'Dutch Global Virtual', 'Dutch Global','vatsim','Y'),
(943, 'AZU', 'Azul Linhas A?reas', 'Azul','vatsim','Y'),
(944, 'PTB', 'Passaredo Transportes A?reos', 'Passaredo','vatsim','Y'),
(945, 'EAV', 'East Avia', 'East Avia','vatsim','Y'),
(946, 'LCO', 'LAN Cargo', 'LAN Cargo','vatsim','Y'),
(947, 'FVA', 'FlyVirtual Alliance', 'FlyVirtual','vatsim','Y'),
(948, 'LEG', 'Legends of the Skies Virtual Aerobatics', 'Legend','vatsim','Y'),
(949, 'STH', 'SouthVirtual', 'South','vatsim','Y'),
(950, 'IST', 'Istanbul Virtual Airlines', 'Istanbul','vatsim','Y'),
(951, 'AVI', 'L''Avion', 'Elysair','vatsim','Y'),
(952, 'FDC', 'Freight Dogs Virtual', 'Freight Dogs','vatsim','Y'),
(953, 'BCN', 'BC North', 'BC North','vatsim','Y'),
(954, 'AVF', 'Archerfield Virtual Aero Club', 'Archer','vatsim','Y'),
(955, 'DUB', 'Dubai Air Wing', 'Dubai','vatsim','Y'),
(956, 'USF', 'Unity Security Force', 'U-SEC','vatsim','Y'),
(957, 'JWB', 'JetWay Brasil', 'Jetway','vatsim','Y'),
(958, 'ARA', 'Arik Air', 'Arik Air','vatsim','Y'),
(959, 'ENJ', 'Enerjet', 'Enerjet','vatsim','Y'),
(960, 'AEI', 'Air Italy Polska', 'Polish Bird','vatsim','Y'),
(961, 'JIA', 'PSA Airlines', 'Blue Streak','vatsim','Y'),
(962, 'CGL', 'Seagle Air', 'Seagle','vatsim','Y'),
(963, 'PLC', 'Poland Cargo', 'Poland Cargo','vatsim','Y'),
(964, 'AFV', 'Australian Frontier Virtual Airlines', 'Australian Frontier','vatsim','Y'),
(965, 'PGU', 'Air Prague', 'Air Prague','vatsim','Y'),
(966, 'VTK', 'Vostok Airlines', 'Vostok','vatsim','Y'),
(967, 'AGJ', 'Air GREECE Virtual', 'Air Greece','vatsim','Y'),
(968, 'FYE', 'flyeire', 'Eire','vatsim','Y'),
(969, 'FDB', 'flydubai', 'Fly Dubai','vatsim','Y'),
(970, 'HCW', 'Star1 Airlines', 'Hermis','vatsim','Y'),
(971, 'VBH', 'Virgin Australia', 'Bluey','vatsim','Y'),
(972, 'MAA', 'Mas Air', 'Mas Air','vatsim','Y'),
(973, 'RCF', 'Aeroflot-Cargo', 'Aeroflot Cargo','vatsim','Y'),
(974, 'MXI', 'MexicanaLink', 'Link','vatsim','Y'),
(975, 'DCS', 'DC Aviation', 'Twin Star','vatsim','Y'),
(976, 'QLK', 'QantasLink', 'Q-Link','vatsim','Y'),
(977, 'KSK', 'Kesuk Charters', 'Mojo','vatsim','Y'),
(978, 'PFV', 'Pacific Frontier', 'Pacific Frontier','vatsim','Y'),
(979, 'FIV', 'CitationAir', 'Fivestar','vatsim','Y'),
(980, 'ACH', 'Air-Child Virtual Air', 'Air Child','vatsim','Y'),
(981, 'FIR', 'First Air', 'First Air','vatsim','Y'),
(982, 'MOS', 'Moscow Air Service', 'Moscow','vatsim','Y'),
(983, 'ARP', 'Airprofessional Virtual Airline', 'Air Pro','vatsim','Y'),
(984, 'EMP', 'Empire Airlines', 'Empire','vatsim','Y'),
(985, 'ESG', 'Estonian Air Regional', 'Estonian Regional','vatsim','Y'),
(986, 'EXK', 'Executive Airlines', 'Executive Eagle','vatsim','Y'),
(987, 'FFR', 'Fischer Air Virtual', 'Fischer','vatsim','Y'),
(988, 'SKP', 'Skytrans Airlines', 'Skytrans','vatsim','Y'),
(989, 'SMX', 'Alitalia Express', 'Aliexpress','vatsim','Y'),
(990, 'GMT', 'Magnicharters', 'Magni','vatsim','Y'),
(991, 'TAO', 'Aeromar', 'Aeromar','vatsim','Y'),
(992, 'ERR', 'Era Alaska', 'Era','vatsim','Y'),
(993, 'TUI', 'TUIfly', 'TUIJET','vatsim','Y'),
(994, 'NSX', 'North Star Executive', '','vatsim','Y'),
(995, 'SQH', 'SeaPort Airlines', 'Sasquatch','vatsim','Y'),
(996, 'RBY', 'Vision Airlines', 'Ruby','vatsim','Y'),
(997, 'NCR', 'National Cargo', 'National Cargo','vatsim','Y'),
(998, 'PALC', 'Philippine Airlines Cargo', '','vatsim','Y'),
(999, 'SBU', 'St. Barth Commuter', 'Black Fin','vatsim','Y'),
(1000, 'GPD', 'TradeWind Aviation', 'Goodspeed','vatsim','Y'),
(1001, 'ZXP', 'Dutch Police', '','vatsim','Y'),
(1002, 'HXT', 'H?xter-Lufttransport', 'Huxori','vatsim','Y'),
(1003, 'GRK', 'Global-Aero', 'Global Aero','vatsim','Y'),
(1004, 'RGO', 'Argo', 'Argos','vatsim','Y'),
(1005, 'SXR', 'SkyExpress', 'Skystorm','vatsim','Y'),
(1006, 'NGF', 'Angel Flight', 'Angel Flight','vatsim','Y'),
(1007, 'CFA', 'Catfish Air', 'Catfish','vatsim','Y'),
(1008, 'DSM', 'LAN Argentina', 'LAN A R','vatsim','Y'),
(1009, 'NDR', 'Nordair Virtuel', '','vatsim','Y'),
(1010, 'SSW', 'Sunshine Airways', '','vatsim','Y'),
(1011, 'R', 'United States Army', '','vatsim','Y'),
(1012, 'FAU', 'Uruguayan Air Force', '','vatsim','Y'),
(1013, 'FDL', 'Farmingdale State College', 'FARMINGDALE STATE','vatsim','Y'),
(1014, 'AWQ', 'Indonesia AirAsia', 'Wagon Air','vatsim','Y'),
(1015, 'AIQ', 'Thai AirAsia', 'Thai Asia','vatsim','Y'),
(1016, 'FLR', 'Florilair', '','vatsim','Y'),
(1017, 'KOR', 'Air Koryo', 'Air Koryo','vatsim','Y'),
(1018, 'DNU', 'DOT LT', 'Danu','vatsim','Y'),
(1019, 'JTG', 'Jet Time', 'JetTime','vatsim','Y'),
(1020, 'HAX', 'Benair', 'Scoop','vatsim','Y'),
(1021, 'AAS', 'Askari Aviation', 'Al-Aas','vatsim','Y'),
(1022, 'NWS', 'Nordwind Airlines', 'Nordwind','vatsim','Y'),
(1023, 'MDT', 'Sundt Air', 'Midnight','vatsim','Y'),
(1024, 'MLD', 'Air Moldova', 'Air Moldova','vatsim','Y'),
(1025, 'TTN', 'Globe Cargo - Titan', 'Titan','vatsim','Y'),
(1026, 'EUL', 'EUROLINE', 'Euroline','vatsim','Y'),
(1027, 'PCM', 'West Air', 'Pac Valley','vatsim','Y'),
(1028, 'SYR', 'Syrian Air', 'Syrianair','vatsim','Y'),
(1029, 'KFR', 'Kingfisher Airlines', 'Kingfisher','vatsim','Y'),
(1030, 'RED', 'Red Cross', 'Red Cross','vatsim','Y'),
(1031, 'AOA', 'Apollo Airlines Virtual', 'Apollo','vatsim','Y'),
(1032, 'AXX', 'Alliance Airways', 'Alliance','vatsim','Y'),
(1033, 'PLS', 'Pulse Air', 'Pulse Air','vatsim','Y'),
(1034, 'VER', 'Verazano Virtual', 'Verazano','vatsim','Y'),
(1035, 'VSB', 'Verazano Cargo', 'Skybridge','vatsim','Y'),
(1036, 'VEV', 'Verazano Connections', 'Bridgeflight','vatsim','Y'),
(1037, 'SGB', 'Sky King', 'Songbird','vatsim','Y'),
(1038, 'SRK', 'Sky Work Airlines', 'Skyfox','vatsim','Y'),
(1039, 'GAP', 'Airphil Express', 'Orient Pacific','vatsim','Y'),
(1040, 'AYT', 'Antalya', 'Antalya','vatsim','Y'),
(1041, 'CAP', 'Civil Air Patrol', 'CAP','vatsim','Y'),
(1042, 'BLR', 'Atlantic Coast Airlines', 'Blue Ridge','vatsim','Y'),
(1043, 'UTA', 'UTair Aviation', 'UTair','vatsim','Y'),
(1044, 'utx', 'UTair Express', 'UTair Express','vatsim','Y'),
(1045, 'EJM', 'Executive Jet Management', 'Jet Speed','vatsim','Y'),
(1046, 'DTH', 'Tassili Airlines', 'Tassili Air','vatsim','Y'),
(1047, 'GGN', 'Air Georgian', 'Georgian','vatsim','Y'),
(1048, 'HCC', 'Holidays Czech Airlines', 'Czech Holidays','vatsim','Y'),
(1049, 'IMP', 'Hellenic Imperial Airways', 'Imperial','vatsim','Y'),
(1050, 'CYX', 'Cayman Express', 'Cayman Express','vatsim','Y'),
(1051, 'KIWA', 'Australian Army Kiowa', 'Kiowa','vatsim','Y'),
(1052, 'BLHK', 'Australian Army Blackhawk', 'Blackhawk','vatsim','Y'),
(1053, 'TIGR', 'Australian Army Tiger', 'Tiger','vatsim','Y'),
(1054, 'CHNK', 'Australian Army Chinook', 'Chinook','vatsim','Y'),
(1055, 'RON', 'Our Airline', 'Air Nauru','vatsim','Y'),
(1056, 'SXD', 'SunExpress', 'Sun Express','vatsim','Y'),
(1057, 'EXH', 'G5 Executive', 'Batman','vatsim','Y'),
(1058, 'AZI', 'Astra Airlines', 'Greek Star','vatsim','Y'),
(1059, 'QJJ', 'Algerian Air Force', 'Algerian Air Force','vatsim','Y'),
(1060, 'UAT', 'Ukraine Atlantic', 'Ukraine Atlantic','vatsim','Y'),
(1061, 'PVA', 'Phoenix Virtual Airways', '','vatsim','Y');
