CREATE TABLE acars_label (
  id serial,
  label varchar(3) NOT NULL,
  title varchar(500) NOT NULL,
  PRIMARY KEY (id)
);

TRUNCATE TABLE acars_label;

INSERT INTO acars_label (id, label, title) VALUES
(1, '00', 'Emergency situation report'),
(2, '2S', 'Weather request'),
(3, '2U', 'Weather'),
(4, '4M', 'Cargo information'),
(5, '51', 'Ground GMT request/report'),
(6, '52', 'Ground UTC request/report'),
(7, '54', 'Aircrew initiated voice contact request'),
(8, '57', 'Alternate aircrew initiated position report'),
(9, '5D', 'Automatic Terminal Information Service (ATIS) request'),
(10, '5P', 'Temporary suspension of ACARS'),
(11, '5R', 'Aircraft initiated position report'),
(12, '5U', 'Weather request'),
(13, '5Y', 'Revision to previous ETA'),
(14, '5Z', 'Airline designated downlink'),
(15, '7A', 'Aircraft initiated engine data'),
(16, '7B', 'Aircraft initiated misc.message'),
(17, 'A1', 'Deliver oceanic clearance'),
(18, 'A2', 'Deliver departure clearance'),
(19, 'A4', 'Acknowledge PDC'),
(20, 'A5', 'Request position report'),
(21, 'A6', 'Request ADS report'),
(22, 'A7', 'Forward free text to aircraft'),
(23, 'A8', 'Deliver departure slot'),
(24, 'A9', 'Deliver Automatic Terminal Information Service (ATIS) information'),
(25, 'A0', 'Automatic Terminal Information Service (ATIS) Facilities notification'),
(26, 'B1', 'Request oceanic clearance'),
(27, 'B2', 'Request oceanic readback'),
(28, 'B3', 'Request departure clearance'),
(29, 'B4', 'Acknowledge departure clearance'),
(30, 'B5', 'Provide position report'),
(31, 'B6', 'Provide ADS report'),
(32, 'B7', 'Forward free text to ATS'),
(33, 'B8', 'Request departure slot'),
(34, 'B9', 'Request Automatic Terminal Information Service (ATIS) information'),
(35, 'C0', 'Uplink message to all cockpit printers'),
(36, 'C1', 'Uplink message to cockpit printer #1'),
(37, 'C2', 'Uplink message to cockpit printer #2'),
(38, 'C3', 'Uplink message to cockpit printer #3'),
(39, 'CA', 'Printer status = error'),
(40, 'CB', 'Printer status = busy'),
(41, 'CC', 'Printer status = local'),
(42, 'CD', 'Printer status = no paper'),
(43, 'CE', 'Printer status = buffer overrun'),
(44, 'CF', 'Printer status = reserved'),
(45, 'F3', 'Dedicated transceiver advisory'),
(46, 'H1', 'Message to/from terminal'),
(47, 'HX', 'Undelivered uplink report'),
(48, 'M1', 'IATA Departure message'),
(49, 'M2', 'IATA Arrival message'),
(50, 'M3', 'IATA Return to ramp message'),
(51, 'M4', 'IATA Return from airborne message'),
(52, 'Q0', 'ACARS link test'),
(53, 'Q1', 'ETA Departure/arrival reports'),
(54, 'Q2', 'ETA reports'),
(55, 'Q3', 'Clock update'),
(56, 'Q4', 'Voice circuit busy'),
(57, 'Q5', 'Unable to process uplinked messages'),
(58, 'Q6', 'Voice-to-ACARS change-over'),
(59, 'Q7', 'Delay message'),
(60, 'QA', 'Out/fuel report'),
(61, 'QB', 'Off report'),
(62, 'QC', 'On report'),
(63, 'QD', 'In/fuel report'),
(64, 'QE', 'Out/fuel destination report'),
(65, 'QF', 'Off/destination report'),
(66, 'QG', 'Out/return in report'),
(67, 'QH', 'Out report'),
(68, 'QK', 'Landing report'),
(69, 'QL', 'Arrival report'),
(70, 'QM', 'Arrival information report'),
(71, 'QN', 'Diversion report'),
(72, 'QX', 'Intercept'),
(73, 'RA', 'Command aircraft terminal to transmit data'),
(74, 'RB', 'Response of aircraft terminal to RA message'),
(75, '8X', 'Uplink ATIS Information'),
(76, 'AA', 'ATCCommunications'),
(77, 'AB', 'Terminal Weather Information for Pilots (TWIP)'),
(78, 'AC', 'Pushback Clearance'),
(79, 'AD', 'Expected Taxi Clearance'),
(80, 'AF', 'CPC Command Response'),
(81, 'B0', 'ATS Facility Notification (AFN)'),
(82, 'BA', 'ATCCommunications'),
(83, 'BB', 'Terminal Weather Information for Pilots'),
(84, 'BC', 'Pushback Clearance Request'),
(85, 'BD', 'Expected Taxi Clearance Request'),
(86, 'BE', 'CPC Log-on/Log-off Request'),
(87, 'BF', 'CPC WILCO/UnassignedBLE Response'),
(88, 'H2', 'Meteorological Report '),
(89, 'H3', 'Icing Report'),
(90, 'S1', 'VHF Network Statistics Report'),
(91, 'S2', 'VHF Performance Report'),
(92, 'S3', 'LRU Configuration Report'),
(93, 'SA', 'Media Advisory'),
(94, 'SQ', 'Squitter Message'),
(95, 'X1', 'Service Provider Defined DSP');

