CREATE TABLE IF NOT EXISTS marine_archive (
  marine_archive_id serial,
  fammarine_id varchar(50) NOT NULL,
  ident varchar(255),
  mmsi varchar(255),
  imo varchar(255),
  type varchar(255),
  departure_port_code varchar(10),
  departure_port_name varchar(255),
  departure_port_city varchar(255),
  departure_port_country varchar(255),
  departure_port_date timestamp NULL DEFAULT NULL,
  arrival_port_code varchar(10),
  arrival_port_name varchar(255),
  arrival_port_city varchar(255),
  arrival_port_country varchar(255),
  arrival_port_date timestamp NULL DEFAULT NULL,
  status varchar(255),
  over_country varchar(255),
  date timestamp NOT NULL,
  latitude float NOT NULL,
  longitude float NOT NULL,
  heading integer NOT NULL,
  ground_speed integer,
  format_source varchar(255) DEFAULT NULL,
  source_name varchar(255) DEFAULT NULL,
  PRIMARY KEY (marine_archive_id)
);

