CREATE TABLE marine_mid (
  mid integer DEFAULT NULL,
  country varchar(255) DEFAULT NULL,
  alpha2 varchar(2) DEFAULT NULL,
  alpha3 varchar(3) DEFAULT NULL
);

ALTER TABLE marine_mid ADD UNIQUE (mid);

INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (201, 'Albania (Republic of)', 'AL', 'ALB');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (202, 'Andorra (Principality of)', 'AD', 'AND');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (203, 'Austria', 'AT', 'AUT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (204, 'Azores', '', 'AZC');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (205, 'Belgium', 'BE', 'BEL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (206, 'Belarus (Republic of)', 'BY', 'BLR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (207, 'Bulgaria (Republic of)', 'BG', 'BUL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (208, 'Vatican City State', 'VA', 'VAT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (209, 'Cyprus (Republic of)', 'CY', 'CYP');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (210, 'Cyprus (Republic of)', 'CY', 'CYP');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (211, 'Germany (Federal Republic of)', 'DE', 'GER');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (212, 'Cyprus (Republic of)', 'CY', 'CYP');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (213, 'Georgia', 'GE', 'GOG');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (214, 'Moldova (Republic of)', 'MD', 'MOL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (215, 'Malta', 'MT', 'MAL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (216, 'Armenia (Republic of)', 'AM', 'ARM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (218, 'Germany (Federal Republic of)', 'DE', 'GER');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (219, 'Denmark', 'DK', 'DEN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (220, 'Denmark', 'DK', 'DEN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (224, 'Spain', 'ES', 'SPA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (225, 'Spain', 'ES', 'SPA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (226, 'France', 'FX', 'FRA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (227, 'France', 'FX', 'FRA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (228, 'France', 'FX', 'FRA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (229, 'Malta', 'MT', 'MAL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (230, 'Finland', 'FI', 'FIN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (231, 'Faroe Islands', 'FO', 'FAR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (232, 'United Kingdom of Great Britain and Northern Ireland', 'GB', 'UKM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (233, 'United Kingdom of Great Britain and Northern Ireland', 'GB', 'UKM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (234, 'United Kingdom of Great Britain and Northern Ireland', 'GB', 'UKM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (235, 'United Kingdom of Great Britain and Northern Ireland', 'GB', 'UKM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (236, 'Gibraltar', 'GI', 'GIB');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (237, 'Greece', 'GR', 'GRE');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (238, 'Croatia (Republic of)', 'HR', 'CRT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (239, 'Greece', 'GR', 'GRE');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (240, 'Greece', 'GR', 'GRE');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (241, 'Greece', 'GR', 'GRE');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (242, 'Morocco (Kingdom of)', 'MA', 'MOR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (243, 'Hungary (Republic of)', 'HU', 'HUN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (244, 'Netherlands (Kingdom of the)', 'NL', 'NET');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (245, 'Netherlands (Kingdom of the)', 'NL', 'NET');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (246, 'Netherlands (Kingdom of the)', 'NL', 'NET');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (247, 'Italy', 'IT', 'ITA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (248, 'Malta', 'MT', 'MAL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (249, 'Malta', 'MT', 'MAL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (250, 'Ireland', 'IE', 'IRE');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (251, 'Iceland', 'IS', 'ICE');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (252, 'Liechtenstein (Principality of)', 'LI', 'LIE');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (253, 'Luxembourg', 'LU', 'LUX');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (254, 'Monaco (Principality of)', 'MC', 'MON');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (255, 'Madeira', '', 'MAE');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (256, 'Malta', 'MT', 'MAL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (257, 'Norway', 'NO', 'NOR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (258, 'Norway', 'NO', 'NOR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (259, 'Norway', 'NO', 'NOR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (261, 'Poland (Republic of)', 'PL', 'POL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (262, 'Montenegro', 'ME', 'MNT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (263, 'Portugal', 'PT', 'POR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (264, 'Romania', 'RO', 'ROM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (265, 'Sweden', 'SE', 'SWE');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (266, 'Sweden', 'SE', 'SWE');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (267, 'Slovak Republic', 'SK', 'SLV');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (268, 'San Marino (Republic of)', 'SM', 'SAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (269, 'Switzerland (Confederation of)', 'CH', 'SWT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (270, 'Czech Republic', 'CZ', 'CZH');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (271, 'Turkey', 'TR', 'TUR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (272, 'Ukraine', 'UA', 'UKR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (273, 'Russian Federation', 'RU', 'RUS');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (274, 'The Former Yugoslav Republic of Macedonia', 'MK', 'MCD');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (275, 'Latvia (Republic of)', 'LV', 'LAT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (276, 'Estonia (Republic of)', 'EE', 'EST');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (277, 'Lithuania (Republic of)', 'LT', 'LIT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (278, 'Slovenia (Republic of)', 'SI', 'SVN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (279, 'Serbia (Republic of)', 'RS', 'SER');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (301, 'Anguilla', 'AI', 'ANA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (303, 'Alaska (State of)', '', 'ALA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (304, 'Antigua and Barbuda', 'AG', 'ANT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (305, 'Antigua and Barbuda', 'AG', 'ANT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (306, 'Netherlands Antilles', 'NL', 'NEA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (307, 'Aruba', 'AW', 'ARU');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (308, 'Bahamas (Commonwealth of the)', 'BS', 'BAA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (309, 'Bahamas (Commonwealth of the)', 'BS', 'BAA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (310, 'Bermuda', 'BM', 'BER');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (311, 'Bahamas (Commonwealth of the)', 'BS', 'BAA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (312, 'Belize', 'BZ', 'BEZ');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (314, 'Barbados', 'BB', 'BAR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (316, 'Canada', 'CA', 'CAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (319, 'Cayman Islands', 'KY', 'CAY');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (321, 'Costa Rica', 'CR', 'COS');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (323, 'Cuba', 'CU', 'CUB');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (325, 'Dominica (Commonwealth of)', 'DM', 'DOM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (327, 'Dominican Republic', 'DO', 'DOR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (329, 'Guadeloupe (French Department of)', 'GP', 'GUA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (330, 'Grenada', 'GD', 'GRA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (331, 'Greenland', 'GL', 'GRN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (332, 'Guatemala (Republic of)', 'GT', 'GUT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (334, 'Honduras (Republic of)', 'HN', 'HON');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (336, 'Haiti (Republic of)', 'HT', 'HAI');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (338, 'United States of America', 'US', 'USA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (339, 'Jamaica', 'JM', 'JAM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (341, 'Saint Kitts and Nevis (Federation of)', 'KN', 'SKN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (343, 'Saint Lucia', 'LC', 'SLU');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (345, 'Mexico', 'MX', 'MEX');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (347, 'Martinique (French Department of)', 'MQ', 'MTQ');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (348, 'Montserrat', 'MS', 'MOT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (350, 'Nicaragua', 'NI', 'NIC');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (351, 'Panama (Republic of)', 'PA', 'PAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (352, 'Panama (Republic of)', 'PA', 'PAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (353, 'Panama (Republic of)', 'PA', 'PAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (354, 'Panama (Republic of)', 'PA', 'PAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (355, 'Panama (Republic of)', 'PA', 'PAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (356, 'Panama (Republic of)', 'PA', 'PAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (357, 'Panama (Republic of)', 'PA', 'PAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (358, 'Puerto Rico', 'PR', 'PUE');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (359, 'El Salvador (Republic of)', 'SV', 'ELS');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (361, 'Saint Pierre and Miquelon (Territorial Collectivity of)', 'PM', 'SPI');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (362, 'Trinidad and Tobago', 'TT', 'TAT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (364, 'Turks and Caicos Islands', 'TC', 'TUK');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (366, 'United States of America', 'US', 'USA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (367, 'United States of America', 'US', 'USA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (368, 'United States of America', 'US', 'USA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (369, 'United States of America', 'US', 'USA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (370, 'Panama (Republic of)', 'PA', 'PAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (371, 'Panama (Republic of)', 'PA', 'PAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (372, 'Panama (Republic of)', 'PA', 'PAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (373, 'Panama (Republic of)', 'PA', 'PAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (375, 'Saint Vincent and the Grenadines', 'VC', 'SVG');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (376, 'Saint Vincent and the Grenadines', 'VC', 'SVG');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (377, 'Saint Vincent and the Grenadines', 'VC', 'SVG');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (378, 'British Virgin Islands', 'VG', 'BVI');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (379, 'United States Virgin Islands', 'VI', 'USV');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (401, 'Afghanistan', 'AF', 'AFG');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (403, 'Saudi Arabia (Kingdom of)', 'SA', 'SAU');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (405, 'Bangladesh (People''s Republic of)', 'BD', 'BAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (408, 'Bahrain (Kingdom of)', 'BH', 'BAH');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (410, 'Bhutan (Kingdom of)', 'BT', 'BHU');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (412, 'China (People''s Republic of)', 'CN', 'CHN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (413, 'China (People''s Republic of)', 'CN', 'CHN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (414, 'China (People''s Republic of)', 'CN', 'CHN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (416, 'Taiwan (Province of China)', 'TW', 'TAI');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (417, 'Sri Lanka (Democratic Socialist Republic of)', 'LK', 'SRI');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (419, 'India (Republic of)', 'IN', 'IND');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (422, 'Iran (Islamic Republic of)', 'IR', 'IRN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (423, 'Azerbaijani Republic', 'AZ', 'AZR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (425, 'Iraq (Republic of)', 'IQ', 'IRQ');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (428, 'Israel (State of)', 'IL', 'ISR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (431, 'Japan', 'JP', 'JPN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (432, 'Japan', 'JP', 'JPN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (434, 'Turkmenistan', 'TM', 'TKM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (436, 'Kazakhstan (Republic of)', 'KZ', 'KAZ');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (437, 'Uzbekistan (Republic of)', 'UZ', 'UZB');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (438, 'Jordan (Hashemite Kingdom of)', 'JO', 'JOR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (440, 'Korea (Republic of)', 'KR', 'KOR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (441, 'Korea (Republic of)', 'KR', 'KOR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (443, 'Palestine', 'PS', 'PAA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (445, 'Democratic People''s Republic of Korea', 'KP', 'KDR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (447, 'Kuwait (State of)', 'KW', 'KUW');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (450, 'Lebanon', 'LB', 'LEB');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (451, 'Kyrgyz Republic', 'KG', 'KYR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (453, 'Macao (Special Administrative Region of China)', 'MO', 'MAC');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (455, 'Maldives (Republic of)', 'MV', 'MAV');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (457, 'Mongolia', 'MN', 'MNG');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (459, 'Nepal (Federal Democratic Republic of)', 'NP', 'NEP');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (461, 'Oman (Sultanate of)', 'OM', 'OMN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (463, 'Pakistan (Islamic Republic of)', 'PK', 'PAK');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (466, 'Qatar (State of)', 'QA', 'QAT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (468, 'Syrian Arab Republic', 'SY', 'SYR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (470, 'United Arab Emirates', 'AE', 'UAE');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (472, 'Tajikistan', 'TJ', 'TJK');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (473, 'Yemen (Republic of)', 'YE', 'YEM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (475, 'Yemen (Republic of)', 'YE', 'YEM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (477, 'Hong Kong (Special Administrative Region of China)', 'HK', 'HKG');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (478, 'Bosnia and Herzegovina', 'BA', 'BOS');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (501, 'Adelie Land', '', 'ADE');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (503, 'Australia', 'AU', 'AUS');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (506, 'Myanmar (Union of)', 'MM', 'BUR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (508, 'Brunei Darussalam', 'BN', 'BRU');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (510, 'Micronesia (Federated States of)', 'FM', 'MIC');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (511, 'Palau (Republic of)', 'PW', 'PAL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (512, 'New Zealand', 'NZ', 'NZL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (514, 'Cambodia (Kingdom of)', 'KH', 'CMB');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (515, 'Cambodia (Kingdom of)', 'KH', 'CMB');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (516, 'Christmas Island (Indian Ocean)', 'CX', 'CHR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (518, 'Cook Islands', 'CK', 'COO');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (520, 'Fiji (Republic of)', 'FJ', 'FIJ');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (523, 'Cocos (Keeling) Islands', 'CC', 'COC');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (525, 'Indonesia (Republic of)', 'ID', 'INO');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (529, 'Kiribati (Republic of)', 'KI', 'KIR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (531, 'Lao People''s Democratic Republic', 'LA', 'LAO');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (533, 'Malaysia', 'MY', 'MLY');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (536, 'Northern Mariana Islands (Commonwealth of the)', 'MP', 'MAI');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (538, 'Marshall Islands (Republic of the)', 'MH', 'MAR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (540, 'New Caledonia', 'NC', 'NCA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (542, 'Niue', 'NU', 'NIU');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (544, 'Nauru (Republic of)', 'NR', 'NAU');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (546, 'French Polynesia', 'PF', 'PLY');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (548, 'Philippines (Republic of the)', 'PH', 'PHI');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (553, 'Papua New Guinea', 'PG', 'PAP');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (555, 'Pitcairn Island', 'PN', 'PIT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (557, 'Solomon Islands', 'SB', 'SOL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (559, 'American Samoa', 'AS', 'ASA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (561, 'Samoa (Independent State of)', 'WS', 'WSA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (563, 'Singapore (Republic of)', 'SG', 'SIN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (564, 'Singapore (Republic of)', 'SG', 'SIN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (565, 'Singapore (Republic of)', 'SG', 'SIN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (566, 'Singapore (Republic of)', 'SG', 'SIN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (567, 'Thailand', 'TH', 'THA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (570, 'Tonga (Kingdom of)', 'TO', 'TON');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (572, 'Tuvalu', 'TV', 'TUV');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (574, 'Viet Nam (Socialist Republic of)', 'VN', 'VIE');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (576, 'Vanuatu (Republic of)', 'VU', 'VAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (577, 'Vanuatu (Republic of)', 'VU', 'VAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (578, 'Wallis and Futuna Islands', 'WF', 'WAL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (601, 'South Africa (Republic of)', 'ZA', 'SAF');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (603, 'Angola (Republic of)', 'AO', 'ANG');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (605, 'Algeria (People''s Democratic Republic of)', 'DZ', 'ALG');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (607, 'Saint Paul and Amsterdam Islands', '', 'SPL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (608, 'Ascension Island', 'AC', 'ASC');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (609, 'Burundi (Republic of)', 'BI', 'BUI');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (610, 'Benin (Republic of)', 'BJ', 'BEN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (611, 'Botswana (Republic of)', 'BW', 'BOT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (612, 'Central African Republic', 'CF', 'CAR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (613, 'Cameroon (Republic of)', 'CM', 'CAM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (615, 'Congo (Republic of the)', 'CG', 'CON');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (616, 'Comoros (Union of the)', 'KM', 'COM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (617, 'Cape Verde (Republic of)', 'CV', 'CAP');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (618, 'Crozet Archipelago', '', 'CRP');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (619, 'C?te d''Ivoire (Republic of)', 'CI', 'IVO');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (620, 'Comoros (Union of the)', 'KM', 'COM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (621, 'Djibouti (Republic of)', 'DJ', 'DJI');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (622, 'Egypt (Arab Republic of)', 'EG', 'EGY');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (624, 'Ethiopia (Federal Democratic Republic of)', 'ET', 'ETH');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (625, 'Eritrea', 'ER', 'ERT');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (626, 'Gabonese Republic', 'GA', 'GAB');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (627, 'Ghana', 'GH', 'GHA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (629, 'Gambia (Republic of the)', 'GM', 'GAM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (630, 'Guinea-Bissau (Republic of)', 'GW', 'GUB');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (631, 'Equatorial Guinea (Republic of)', 'GQ', 'EQG');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (632, 'Guinea (Republic of)', 'GN', 'GUN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (633, 'Burkina Faso', 'BF', 'BUF');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (634, 'Kenya (Republic of)', 'KE', 'KEN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (635, 'Kerguelen Islands', '', 'KER');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (636, 'Liberia (Republic of)', 'LR', 'LIB');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (637, 'Liberia (Republic of)', 'LR', 'LIB');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (638, 'South Sudan', 'SS', 'SSD');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (642, 'Socialist People''s Libyan Arab Jamahiriya', 'LY', 'LBY');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (644, 'Lesotho (Kingdom of)', 'LS', 'LES');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (645, 'Mauritius (Republic of)', 'MU', 'MAU');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (647, 'Madagascar (Republic of)', 'MG', 'MAD');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (649, 'Mali (Republic of)', 'ML', 'MLI');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (650, 'Mozambique (Republic of)', 'MZ', 'MOZ');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (654, 'Mauritania (Islamic Republic of)', 'MR', 'MAA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (655, 'Malawi', 'MW', 'MAW');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (656, 'Niger (Republic of the)', 'NE', 'NIG');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (657, 'Nigeria (Federal Republic of)', 'NG', 'NIA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (659, 'Namibia (Republic of)', 'NA', 'NAM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (660, 'Reunion (French Department of)', 'RE', 'REU');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (661, 'Rwanda (Republic of)', 'RW', 'RWA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (662, 'Sudan (Republic of the)', 'SD', 'SUD');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (663, 'Senegal (Republic of)', 'SN', 'SEN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (664, 'Seychelles (Republic of)', 'SC', 'SEY');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (665, 'Saint Helena', 'SH', 'SHE');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (666, 'Somali Democratic Republic', 'SO', 'SOM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (667, 'Sierra Leone', 'SL', 'SIL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (668, 'Sao Tome and Principe (Democratic Republic of)', 'ST', 'SAO');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (669, 'Swaziland (Kingdom of)', 'SZ', 'SWA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (670, 'Chad (Republic of)', 'TD', 'CHA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (671, 'Togolese Republic', 'TG', 'TOG');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (672, 'Tunisia', 'TN', 'TUN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (674, 'Tanzania (United Republic of)', 'TZ', 'TAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (675, 'Uganda (Republic of)', 'UG', 'UGA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (676, 'Democratic Republic of the Congo', 'CD', 'ZAI');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (677, 'Tanzania (United Republic of)', 'TZ', 'TAN');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (678, 'Zambia (Republic of)', 'ZM', 'ZAM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (679, 'Zimbabwe (Republic of)', 'ZW', 'ZIM');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (701, 'Argentine Republic', 'AR', 'ARG');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (710, 'Brazil (Federative Republic of)', 'BR', 'BRA');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (720, 'Bolivia (Plurinational State of)', 'BO', 'BOL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (725, 'Chile', 'CL', 'CHI');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (730, 'Colombia (Republic of)', 'CO', 'COL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (735, 'Ecuador', 'EC', 'ECU');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (740, 'Falkland Islands (Malvinas)', 'FK', 'FAL');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (745, 'Guiana (French Department of)', 'GF', 'GUI');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (750, 'Guyana', 'GY', 'GUY');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (755, 'Paraguay (Republic of)', 'PY', 'PAR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (760, 'Peru', 'PE', 'PER');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (765, 'Suriname (Republic of)', 'SR', 'SUR');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (770, 'Uruguay (Eastern Republic of)', 'UY', 'URU');
INSERT INTO marine_mid (mid, country, alpha2, alpha3) VALUES (775, 'Venezuela (Bolivarian Republic of)', 'VE', 'VEN');
