CREATE TABLE spotter_output (
  spotter_id serial,
  flightaware_id varchar(255) NOT NULL,
  ident varchar(255) DEFAULT NULL,
  registration varchar(255),
  airline_name varchar(255) NOT NULL,
  airline_icao varchar(10) NOT NULL,
  airline_country varchar(255) NOT NULL,
  airline_type varchar(255) NOT NULL,
  aircraft_icao varchar(10) NOT NULL,
  aircraft_name varchar(255) NOT NULL,
  aircraft_manufacturer varchar(255) NOT NULL,
  departure_airport_icao varchar(10) NOT NULL,
  departure_airport_name varchar(255) NOT NULL,
  departure_airport_city varchar(255) NOT NULL,
  departure_airport_country varchar(255) NOT NULL,
  departure_airport_time varchar(20),
  arrival_airport_icao varchar(10) NOT NULL,
  arrival_airport_name varchar(255) NOT NULL,
  arrival_airport_city varchar(255) NOT NULL,
  arrival_airport_country varchar(255) NOT NULL,
  arrival_airport_time varchar(20),
  route_stop varchar(255) NOT NULL,
  date timestamp NOT NULL,
  latitude float NOT NULL,
  longitude float NOT NULL,
  waypoints text NOT NULL,
  altitude integer NOT NULL,
  real_altitude float DEFAULT NULL,
  heading integer NOT NULL,
  ground_speed integer NOT NULL,
  highlight text,
  squawk integer,
  ModeS varchar(255) DEFAULT NULL,
  pilot_id varchar(255),
  pilot_name varchar(255),
  owner_name varchar(255),
  verticalrate integer,
  format_source varchar(255),
  source_name varchar(255) DEFAULT NULL,
  ground integer NOT NULL DEFAULT '0',
  last_ground integer NOT NULL DEFAULT '0',
  last_seen timestamp,
  last_latitude float,
  last_longitude float,
  last_altitude integer,
  last_ground_speed integer,
  real_arrival_airport_icao varchar(10),
  real_arrival_airport_time varchar(20),
  real_departure_airport_icao varchar(10),
  real_departure_airport_time varchar(20),
  PRIMARY KEY (spotter_id)
);
